"""人社部新职业名单。每条带公示日期与官方链接。"""

from __future__ import annotations

# date_status:
#   verified — 找到公示通告日期
#   published_fallback — 未找到公示通告原文，暂用正式发布日，README 标待补充

BATCHES = [
    {
        "batch": 1,
        "batch_name": "2019年第一批",
        "public_comment_date": "2019-01-25",
        "public_comment_end": "2019-01-31",
        "published_date": "2019-04-01",
        "date_status": "verified",
        "document_no": "人社厅发〔2019〕48号",
        "official_url": "https://www.gov.cn/zhengce/zhengceku/2019-09/26/content_5433626.htm",
        "comment_url": "https://www.miiteec.org.cn/news_details?code=709",
        "status": "published",
        "occupations": [
            "人工智能工程技术人员",
            "物联网工程技术人员",
            "大数据工程技术人员",
            "云计算工程技术人员",
            "数字化管理师",
            "建筑信息模型技术员",
            "电子竞技运营师",
            "电子竞技员",
            "无人机驾驶员",
            "农业经理人",
            "物联网安装调试员",
            "工业机器人系统操作员",
            "工业机器人系统运维员",
        ],
    },
    {
        "batch": 2,
        "batch_name": "2020年第二批",
        "public_comment_date": "2020-02-25",
        "public_comment_end": None,
        "published_date": "2020-02-25",
        "date_status": "published_fallback",
        "document_no": "人社厅发〔2020〕17号",
        "official_url": "https://gaokao.chsi.com.cn/gkxx/zybk/202003/20200303/1879316557.html",
        "comment_url": None,
        "status": "published",
        "occupations": [
            "智能制造工程技术人员",
            "工业互联网工程技术人员",
            "虚拟现实工程技术人员",
            "连锁经营管理师",
            "供应链管理师",
            "网约配送员",
            "人工智能训练师",
            "电气电子产品环保检测员",
            "全媒体运营师",
            "健康照护师",
            "呼吸治疗师",
            "出生缺陷防控咨询师",
            "康复辅助技术咨询师",
            "无人机装调检修工",
            "铁路综合维修工",
            "装配式建筑施工员",
        ],
    },
    {
        "batch": 3,
        "batch_name": "2020年第三批",
        "public_comment_date": "2020-06-28",
        "public_comment_end": None,
        "published_date": "2020-06-28",
        "date_status": "published_fallback",
        "document_no": "人社厅发〔2020〕73号",
        "official_url": "https://www.gov.cn/zhengce/zhengceku/2020-07/09/content_5525254.htm",
        "comment_url": "http://www.cac.gov.cn/2020-07/06/c_1595589181850322.htm",
        "status": "published",
        "occupations": [
            "区块链工程技术人员",
            "城市管理网格员",
            "互联网营销师",
            "信息安全测试员",
            "区块链应用操作员",
            "在线学习服务师",
            "社群健康助理员",
            "老年人能力评估师",
            "增材制造设备操作员",
        ],
    },
    {
        "batch": 4,
        "batch_name": "2021年第四批",
        "public_comment_date": "2021-03-18",
        "public_comment_end": None,
        "published_date": "2021-03-18",
        "date_status": "published_fallback",
        "document_no": "人社厅发〔2021〕17号",
        "official_url": "https://chinajob.mohrss.gov.cn/c/2021-03-19/296305.shtml",
        "comment_url": None,
        "status": "published",
        "occupations": [
            "集成电路工程技术人员",
            "企业合规师",
            "公司金融顾问",
            "易货师",
            "二手车经纪人",
            "汽车救援员",
            "调饮师",
            "食品安全管理师",
            "服务机器人应用技术员",
            "电子数据取证分析师",
            "职业培训师",
            "密码技术应用员",
            "建筑幕墙设计师",
            "碳排放管理员",
            "管廊运维员",
            "酒体设计师",
            "智能硬件装调员",
            "工业视觉系统运维员",
        ],
    },
    {
        "batch": 5,
        "batch_name": "2022年第五批",
        "public_comment_date": "2022-06-14",
        "public_comment_end": "2022-06-20",
        "published_date": "2022-09-01",
        "date_status": "verified",
        "document_no": "纳入《职业分类大典（2022年版）》",
        "official_url": "https://www.gov.cn/xinwen/2022-06/15/content_5695712.htm",
        "comment_url": "https://www.gov.cn/xinwen/2022-06/21/content_5696877.htm",
        "status": "published",
        "occupations": [
            "机器人工程技术人员",
            "增材制造工程技术人员",
            "数据安全工程技术人员",
            "退役军人事务员",
            "数字化解决方案设计师",
            "数据库运行管理员",
            "信息系统适配验证师",
            "数字孪生应用技术员",
            "商务数据分析师",
            "碳汇计量评估师",
            "建筑节能减排咨询师",
            "综合能源服务员",
            "家庭教育指导师",
            "研学旅行指导师",
            "民宿管家",
            "农业数字化技术员",
            "煤提质工",
            "城市轨道交通检修工",
        ],
    },
    {
        "batch": 6,
        "batch_name": "2024年第六批",
        "public_comment_date": "2024-05-24",
        "public_comment_end": "2024-06-07",
        "published_date": "2024-07-25",
        "date_status": "verified",
        "document_no": "人社厅发〔2024〕36号",
        "official_url": "https://www.gov.cn/zhengce/zhengceku/202407/content_6965461.htm",
        "comment_url": "https://chinajob.mohrss.gov.cn/c/2024-08-01/413001.shtml",
        "status": "published",
        "occupations": [
            "生物工程技术人员",
            "口腔卫生技师",
            "网络安全等级保护测评师",
            "云网智能运维员",
            "生成式人工智能系统应用员",
            "工业互联网运维员",
            "智能网联汽车测试员",
            "有色金属现货交易员",
            "用户增长运营师",
            "会展搭建师",
            "文创产品策划运营师",
            "储能电站运维管理员",
            "电能质量管理员",
            "版权经纪人",
            "网络主播",
            "滑雪巡救员",
            "氢基直接还原炼铁工",
            "智能制造系统运维员",
            "智能网联汽车装调运维员",
        ],
    },
    {
        "batch": 7,
        "batch_name": "2025年第七批",
        "public_comment_date": "2025-07-22",
        "public_comment_end": None,
        "published_date": "2025-07-22",
        "date_status": "published_fallback",
        "document_no": "人社部2025年7月22日新闻发布会",
        "official_url": "https://www.xinhuanet.com/edu/20250722/875f221f084f47c0a9790d75f26d73a6/c.html",
        "comment_url": "https://news.cnr.cn/dj/20250723/t20250723_527278128.shtml",
        "status": "published",
        "occupations": [
            "检验检测管理工程技术人员",
            "养老服务师",
            "跨境电商运营管理师",
            "无人机群飞行规划员",
            "装修管家",
            "工伤预防咨询师",
            "电子电路设计师",
            "室内环境治理员",
            "家政服务经理人",
            "电力可靠性管理员",
            "电力聚合运营员",
            "农村集体经济经理人",
            "代用茶加工工",
            "咖啡加工工",
            "碳纤维制品成型制作工",
            "铁氧体磁体制造工",
            "钢结构装配工",
        ],
    },
    {
        "batch": 8,
        "batch_name": "2026年第八批（公示中）",
        "public_comment_date": "2026-07-02",
        "public_comment_end": "2026-07-17",
        "published_date": None,
        "date_status": "verified",
        "document_no": "关于对拟发布船舶岸基管理工程技术人员等职业信息进行公示的公告",
        "official_url": "https://chinajob.mohrss.gov.cn/c/2026-07-06/568023.shtml",
        "comment_url": "https://news.cnr.cn/native/gd/20260703/t20260703_527687693.shtml",
        "status": "public_comment",
        "occupations": [
            "船舶岸基管理工程技术人员",
            "动物实验工程技术人员",
            "数字孪生工程技术人员",
            "具身智能机器人应用技术员",
            "工业产品数字建模师",
            "企业可持续发展规划师",
            "微电网管理员",
            "运动数据分析师",
            "制香香艺师",
            "氢燃料电池制造工",
            "卫星导航设备装调工",
            "电解水制氢工",
        ],
        "job_types": [
            "低空物流员",
            "智能体开发员",
            "新能源汽车检测员",
            "适老化改造设计师",
        ],
    },
]


def iter_new_occupations(version: str) -> list[dict]:
    rows: list[dict] = []
    for b in BATCHES:
        for name in b["occupations"]:
            rows.append(
                {
                    "id": f"newocc.{b['batch']:02d}.{name}",
                    "name": name,
                    "kind": "occupation",
                    "batch": b["batch"],
                    "batch_name": b["batch_name"],
                    "public_comment_date": b["public_comment_date"],
                    "public_comment_end": b["public_comment_end"],
                    "published_date": b["published_date"],
                    "date_status": b["date_status"],
                    "status": b["status"],
                    "document_no": b["document_no"],
                    "official_url": b["official_url"],
                    "comment_url": b["comment_url"],
                    "ontology_version": version,
                }
            )
        for name in b.get("job_types") or []:
            rows.append(
                {
                    "id": f"newocc.{b['batch']:02d}.job.{name}",
                    "name": name,
                    "kind": "job_type",
                    "batch": b["batch"],
                    "batch_name": b["batch_name"],
                    "public_comment_date": b["public_comment_date"],
                    "public_comment_end": b["public_comment_end"],
                    "published_date": b["published_date"],
                    "date_status": b["date_status"],
                    "status": b["status"],
                    "document_no": b["document_no"],
                    "official_url": b["official_url"],
                    "comment_url": b["comment_url"],
                    "ontology_version": version,
                }
            )
    rows.sort(key=lambda r: (r["batch"], r["kind"] != "occupation", r["name"]))
    return rows
