"""大数据、智能系统、物联网方向技能点。宽而浅的骨架。"""

BIGDATA = [
    ("hadoop", "Hadoop", "Hadoop", "Apache Hadoop", "", "cluster.batch-compute", "bigdata"),
    ("mapreduce", "MapReduce", "MapReduce", "Hadoop MapReduce", "hadoop", "cluster.batch-compute", "bigdata"),
    ("hdfs", "HDFS", "HDFS", "Hadoop分布式文件系统", "hadoop", "cluster.batch-compute", "bigdata"),
    ("yarn-hadoop", "YARN", "YARN", "Hadoop YARN", "hadoop", "cluster.batch-compute", "bigdata"),
    ("spark", "Apache Spark", "Apache Spark", "Spark|PySpark|Spark SQL", "", "cluster.batch-compute", "bigdata"),
    ("spark-streaming", "Spark Streaming", "Spark Streaming", "DStream", "spark", "cluster.batch-compute", "bigdata"),
    ("spark-mllib", "Spark MLlib", "Spark MLlib", "MLlib", "spark", "cluster.batch-compute", "bigdata"),
    ("hive", "Hive", "Hive", "Apache Hive", "", "cluster.batch-compute", "bigdata"),
    ("tez", "Tez", "Tez", "Apache Tez", "hive", "cluster.batch-compute", "bigdata"),
    ("pig", "Pig", "Pig", "Apache Pig", "hadoop", "cluster.batch-compute", "bigdata"),
    ("presto", "Presto", "Presto", "PrestoDB|PrestoSQL", "", "cluster.batch-compute", "bigdata"),
    ("trino", "Trino", "Trino", "原PrestoSQL", "", "cluster.batch-compute", "bigdata"),
    ("impala", "Impala", "Impala", "Apache Impala", "", "cluster.batch-compute", "bigdata"),
    ("kudu", "Kudu", "Kudu", "Apache Kudu", "", "cluster.batch-compute", "bigdata"),
    ("tez-none", "", "", "", "", "cluster.batch-compute", "bigdata"),
]

BIGDATA = [r for r in BIGDATA if r[0] != "tez-none"]

BIGDATA += [
    ("flink", "Flink", "Apache Flink", "Flink SQL|PyFlink", "", "cluster.stream", "bigdata"),
    ("kafka", "Kafka", "Apache Kafka", "Kafka Streams", "", "cluster.stream", "bigdata"),
    ("pulsar", "Pulsar", "Apache Pulsar", "流消息Pulsar", "", "cluster.stream", "bigdata"),
    ("storm", "Storm", "Apache Storm", "Twitter Storm", "", "cluster.stream", "bigdata"),
    ("spark-structured-streaming", "Structured Streaming", "Structured Streaming", "Spark结构化流", "spark", "cluster.stream", "bigdata"),
    ("flink-cdc", "Flink CDC", "Flink CDC", "变更数据捕获", "flink", "cluster.stream", "bigdata"),
    ("debezium", "Debezium", "Debezium", "CDC Debezium", "", "cluster.stream", "bigdata"),
    ("canal", "Canal", "Canal", "阿里Canal", "", "cluster.stream", "bigdata"),
    ("maxwell", "Maxwell", "Maxwell", "Zendesk Maxwell", "", "cluster.stream", "bigdata"),
    ("ksqldb", "ksqlDB", "ksqlDB", "Kafka SQL", "kafka", "cluster.stream", "bigdata"),
    ("flink-window", "Flink窗口", "Flink Window", "滚动窗口|滑动窗口", "flink", "cluster.stream", "bigdata"),
    ("watermark", "水位线", "Watermark", "事件时间水位", "flink", "cluster.stream", "bigdata"),
    ("exactly-once", "精确一次语义", "Exactly-Once", "EOS", "flink", "cluster.stream", "bigdata"),
    ("iceberg", "Iceberg", "Apache Iceberg", "数据湖表格式Iceberg", "", "cluster.lakehouse", "bigdata"),
    ("hudi", "Hudi", "Apache Hudi", "Hadoop Upserts Deletes Incremental", "", "cluster.lakehouse", "bigdata"),
    ("delta-lake", "Delta Lake", "Delta Lake", "Databricks Delta", "", "cluster.lakehouse", "bigdata"),
    ("paimon", "Paimon", "Apache Paimon", "Flink Table Store", "", "cluster.lakehouse", "bigdata"),
    ("hive-metastore", "Hive Metastore", "Hive Metastore", "HMS", "hive", "cluster.lakehouse", "bigdata"),
    ("unity-catalog", "Unity Catalog", "Unity Catalog", "Databricks目录", "", "cluster.lakehouse", "bigdata"),
    ("datahub", "DataHub", "DataHub", "LinkedIn DataHub", "", "cluster.lakehouse", "bigdata"),
    ("amundsen", "Amundsen", "Amundsen", "Lyft Amundsen", "", "cluster.lakehouse", "bigdata"),
    ("atlas", "Atlas", "Apache Atlas", "元数据Atlas", "", "cluster.lakehouse", "bigdata"),
    ("ranger", "Ranger", "Apache Ranger", "权限Ranger", "", "cluster.lakehouse", "bigdata"),
    ("clickhouse", "ClickHouse", "ClickHouse", "列存ClickHouse", "", "cluster.olap", "bigdata"),
    ("doris", "Apache Doris", "Apache Doris", "Doris|原Palo", "", "cluster.olap", "bigdata"),
    ("starrocks", "StarRocks", "StarRocks", "原Doris分支", "", "cluster.olap", "bigdata"),
    ("druid", "Druid", "Apache Druid", "时序OLAP", "", "cluster.olap", "bigdata"),
    ("kylin", "Kylin", "Apache Kylin", "立方体Kylin", "", "cluster.olap", "bigdata"),
    ("greenplum", "Greenplum", "Greenplum", "GPDB", "", "cluster.olap", "bigdata"),
    ("vertica", "Vertica", "Vertica", "列式Vertica", "", "cluster.olap", "bigdata"),
    ("teradata", "Teradata", "Teradata", "Teradata Database", "", "cluster.olap", "bigdata"),
    ("snowflake", "Snowflake", "Snowflake", "云数仓Snowflake", "", "cluster.olap", "bigdata"),
    ("bigquery", "BigQuery", "BigQuery", "Google BigQuery", "", "cluster.olap", "bigdata"),
    ("redshift", "Redshift", "Amazon Redshift", "AWS Redshift", "", "cluster.olap", "bigdata"),
    ("synapse", "Azure Synapse", "Azure Synapse", "Synapse Analytics", "", "cluster.olap", "bigdata"),
    ("maxcompute", "MaxCompute", "MaxCompute", "ODPS|阿里云MaxCompute", "", "cluster.olap", "bigdata"),
    ("gaussdb", "GaussDB", "GaussDB", "华为高斯数据库", "", "cluster.olap", "bigdata"),
    ("selectdb", "SelectDB", "SelectDB", "基于Doris", "doris", "cluster.olap", "bigdata"),
    ("byconity", "ByConity", "ByConity", "字节ByConity", "", "cluster.olap", "bigdata"),
    ("mysql", "MySQL", "MySQL", "MariaDB", "", "cluster.db", "bigdata"),
    ("postgresql", "PostgreSQL", "PostgreSQL", "Postgres|PG", "", "cluster.db", "bigdata"),
    ("oracle-db", "Oracle数据库", "Oracle Database", "Oracle DB", "", "cluster.db", "bigdata"),
    ("sqlserver", "SQL Server", "Microsoft SQL Server", "MSSQL", "", "cluster.db", "bigdata"),
    ("mongodb", "MongoDB", "MongoDB", "文档数据库", "", "cluster.db", "bigdata"),
    ("redis", "Redis", "Redis", "缓存Redis", "", "cluster.db", "bigdata"),
    ("elasticsearch", "Elasticsearch", "Elasticsearch", "ES|Elastic Stack", "", "cluster.db", "bigdata"),
    ("opensearch", "OpenSearch", "OpenSearch", "AWS OpenSearch", "", "cluster.db", "bigdata"),
    ("neo4j", "Neo4j", "Neo4j", "图数据库Neo4j", "", "cluster.db", "bigdata"),
    ("tidb", "TiDB", "TiDB", "PingCAP TiDB", "", "cluster.db", "bigdata"),
    ("oceanbase", "OceanBase", "OceanBase", "蚂蚁OceanBase", "", "cluster.db", "bigdata"),
    ("cockroachdb", "CockroachDB", "CockroachDB", "CRDB", "", "cluster.db", "bigdata"),
    ("cassandra", "Cassandra", "Apache Cassandra", "列族Cassandra", "", "cluster.db", "bigdata"),
    ("hbase", "HBase", "Apache HBase", "HBase表", "", "cluster.db", "bigdata"),
    ("dynamodb", "DynamoDB", "Amazon DynamoDB", "AWS DynamoDB", "", "cluster.db", "bigdata"),
    ("couchbase", "Couchbase", "Couchbase", "文档Couchbase", "", "cluster.db", "bigdata"),
    ("influxdb", "InfluxDB", "InfluxDB", "时序Influx", "", "cluster.db", "bigdata"),
    ("timescaledb", "TimescaleDB", "TimescaleDB", "PG时序", "postgresql", "cluster.db", "bigdata"),
    ("dameng", "达梦", "Dameng", "DM数据库", "", "cluster.db", "bigdata"),
    ("kingbase", "人大金仓", "Kingbase", "KingbaseES", "", "cluster.db", "bigdata"),
    ("opengauss", "openGauss", "openGauss", "开源高斯", "", "cluster.db", "bigdata"),
    ("sqlite", "SQLite", "SQLite", "嵌入式SQL", "", "cluster.db", "bigdata"),
    ("memcached", "Memcached", "Memcached", "分布式缓存", "", "cluster.db", "bigdata"),
    ("etcd", "etcd", "etcd", "分布式键值", "", "cluster.db", "bigdata"),
    ("zookeeper", "ZooKeeper", "Apache ZooKeeper", "ZK", "", "cluster.db", "bigdata"),
    ("minio", "MinIO", "MinIO", "对象存储MinIO", "", "cluster.db", "bigdata"),
    ("s3", "Amazon S3", "Amazon S3", "对象存储S3", "", "cluster.db", "bigdata"),
    ("oss", "对象存储OSS", "Alibaba Cloud OSS", "阿里云OSS", "", "cluster.db", "bigdata"),
    ("hdfs-none", "", "", "", "", "cluster.db", "bigdata"),
]

BIGDATA = [r for r in BIGDATA if r[0] != "hdfs-none"]

BIGDATA += [
    ("tableau", "Tableau", "Tableau", "Tableau Desktop", "", "cluster.bi", "bigdata"),
    ("powerbi", "Power BI", "Power BI", "Microsoft Power BI", "", "cluster.bi", "bigdata"),
    ("superset", "Superset", "Apache Superset", "数据可视化Superset", "", "cluster.bi", "bigdata"),
    ("metabase", "Metabase", "Metabase", "开源BI", "", "cluster.bi", "bigdata"),
    ("finebi", "FineBI", "FineBI", "帆软FineBI", "", "cluster.bi", "bigdata"),
    ("qlik", "Qlik", "Qlik", "QlikView|Qlik Sense", "", "cluster.bi", "bigdata"),
    ("looker", "Looker", "Looker", "Google Looker", "", "cluster.bi", "bigdata"),
    ("grafana", "Grafana", "Grafana", "监控可视化", "", "cluster.bi", "bigdata"),
    ("kibana", "Kibana", "Kibana", "Elastic Kibana", "elasticsearch", "cluster.bi", "bigdata"),
    ("dataease", "DataEase", "DataEase", "飞致云DataEase", "", "cluster.bi", "bigdata"),
    ("airflow", "Airflow", "Apache Airflow", "工作流Airflow", "", "cluster.de-tools", "bigdata"),
    ("dolphinscheduler", "DolphinScheduler", "Apache DolphinScheduler", "海豚调度", "", "cluster.de-tools", "bigdata"),
    ("azkaban", "Azkaban", "Azkaban", "LinkedIn Azkaban", "", "cluster.de-tools", "bigdata"),
    ("oozie", "Oozie", "Apache Oozie", "Hadoop工作流", "", "cluster.de-tools", "bigdata"),
    ("datax", "DataX", "DataX", "阿里DataX", "", "cluster.de-tools", "bigdata"),
    ("sqoop", "Sqoop", "Apache Sqoop", "关系库导入Hadoop", "", "cluster.de-tools", "bigdata"),
    ("flume", "Flume", "Apache Flume", "日志采集Flume", "", "cluster.de-tools", "bigdata"),
    ("nifi", "NiFi", "Apache NiFi", "数据流NiFi", "", "cluster.de-tools", "bigdata"),
    ("kettle", "Kettle", "Pentaho Data Integration", "PDI|Kettle ETL", "", "cluster.de-tools", "bigdata"),
    ("informatica", "Informatica", "Informatica", "Informatica PowerCenter", "", "cluster.de-tools", "bigdata"),
    ("talend", "Talend", "Talend", "Talend Open Studio", "", "cluster.de-tools", "bigdata"),
    ("dbt", "dbt", "dbt", "data build tool", "", "cluster.de-tools", "bigdata"),
    ("great-expectations", "Great Expectations", "Great Expectations", "数据质量GE", "", "cluster.de-tools", "bigdata"),
    ("soda", "Soda", "Soda", "Soda SQL", "", "cluster.de-tools", "bigdata"),
    ("spark-sql", "Spark SQL", "Spark SQL", "DataFrame API", "spark", "cluster.de-tools", "bigdata"),
    ("linux", "Linux", "Linux", "GNU/Linux", "", "cluster.de-tools", "bigdata"),
    ("git", "Git", "Git", "版本控制Git", "", "cluster.de-tools", "bigdata"),
    ("github", "GitHub", "GitHub", "gh", "git", "cluster.de-tools", "bigdata"),
    ("gitlab", "GitLab", "GitLab", "gitlab ci", "git", "cluster.de-tools", "bigdata"),
    ("docker", "Docker", "Docker", "容器Docker", "", "cluster.de-tools", "bigdata"),
    ("kubernetes", "Kubernetes", "Kubernetes", "K8s|k8s", "", "cluster.de-tools", "bigdata"),
    ("helm", "Helm", "Helm", "K8s包管理", "kubernetes", "cluster.de-tools", "bigdata"),
    ("terraform", "Terraform", "Terraform", "IaC Terraform", "", "cluster.de-tools", "bigdata"),
    ("ansible", "Ansible", "Ansible", "配置管理Ansible", "", "cluster.de-tools", "bigdata"),
    ("prometheus", "Prometheus", "Prometheus", "监控Prometheus", "", "cluster.de-tools", "bigdata"),
    ("jenkins", "Jenkins", "Jenkins", "持续集成Jenkins", "", "cluster.de-tools", "bigdata"),
    ("github-actions", "GitHub Actions", "GitHub Actions", "GHA", "github", "cluster.de-tools", "bigdata"),
    ("data-governance", "数据治理", "Data Governance", "数据管理", "", "cluster.governance", "bigdata"),
    ("data-quality", "数据质量", "Data Quality", "DQ", "data-governance", "cluster.governance", "bigdata"),
    ("master-data", "主数据管理", "Master Data Management", "MDM", "data-governance", "cluster.governance", "bigdata"),
    ("data-lineage", "数据血缘", "Data Lineage", "血缘分析", "data-governance", "cluster.governance", "bigdata"),
    ("data-masking", "数据脱敏", "Data Masking", "脱敏", "data-governance", "cluster.governance", "bigdata"),
    ("gdpr", "个人数据保护", "GDPR/PIPL", "个保法|GDPR", "data-governance", "cluster.governance", "bigdata"),
    ("data-warehouse", "数据仓库", "Data Warehouse", "数仓|DW", "", "cluster.governance", "bigdata"),
    ("dimensional-model", "维度建模", "Dimensional Modeling", "星型模型|Kimball", "data-warehouse", "cluster.governance", "bigdata"),
    ("data-lake", "数据湖", "Data Lake", "湖仓一体", "", "cluster.lakehouse", "bigdata"),
    ("etl", "ETL", "ETL", "抽取转换加载", "", "cluster.de-tools", "bigdata"),
    ("elt", "ELT", "ELT", "抽取加载转换", "", "cluster.de-tools", "bigdata"),
    ("aws", "Amazon Web Services", "AWS", "亚马逊云", "", "cluster.cloud-data", "bigdata"),
    ("azure", "Microsoft Azure", "Microsoft Azure", "Azure云", "", "cluster.cloud-data", "bigdata"),
    ("gcp", "Google Cloud", "Google Cloud Platform", "GCP", "", "cluster.cloud-data", "bigdata"),
    ("aliyun", "阿里云", "Alibaba Cloud", "Aliyun", "", "cluster.cloud-data", "bigdata"),
    ("tencent-cloud", "腾讯云", "Tencent Cloud", "QCloud", "", "cluster.cloud-data", "bigdata"),
    ("huawei-cloud", "华为云", "Huawei Cloud", "HUAWEI CLOUD", "", "cluster.cloud-data", "bigdata"),
    ("volcengine", "火山引擎", "Volcengine", "字节火山引擎", "", "cluster.cloud-data", "bigdata"),
    ("emr", "EMR", "Amazon EMR", "弹性MapReduce", "aws", "cluster.cloud-data", "bigdata"),
    ("databricks", "Databricks", "Databricks", "湖仓Databricks", "", "cluster.cloud-data", "bigdata"),
    ("flink-sql", "Flink SQL", "Flink SQL", "流批一体SQL", "flink", "cluster.stream", "bigdata"),
    ("kafka-connect", "Kafka Connect", "Kafka Connect", "Connectors", "kafka", "cluster.stream", "bigdata"),
    ("schema-registry", "Schema Registry", "Schema Registry", "Avro Schema", "kafka", "cluster.stream", "bigdata"),
    ("avro", "Avro", "Apache Avro", "序列化Avro", "", "cluster.stream", "bigdata"),
    ("parquet", "Parquet", "Apache Parquet", "列存文件", "", "cluster.lakehouse", "bigdata"),
    ("orc", "ORC", "Apache ORC", "Optimized Row Columnar", "", "cluster.lakehouse", "bigdata"),
    ("arrow", "Apache Arrow", "Apache Arrow", "内存列式Arrow", "", "cluster.batch-compute", "bigdata"),
    ("polars", "Polars", "Polars", "Rust DataFrame", "", "cluster.batch-compute", "bigdata"),
    ("duckdb", "DuckDB", "DuckDB", "嵌入式OLAP", "", "cluster.olap", "bigdata"),
    ("trino-iceberg", "Trino Iceberg", "Trino Iceberg Connector", "查询Iceberg", "trino", "cluster.lakehouse", "bigdata"),
]

SYSTEMS = [
    ("ros", "ROS", "Robot Operating System", "ROS1", "", "cluster.robotics", "intelligent_systems"),
    ("ros2", "ROS 2", "ROS 2", "ROS2|Robot Operating System 2", "", "cluster.robotics", "intelligent_systems"),
    ("gazebo", "Gazebo", "Gazebo", "机器人仿真Gazebo", "", "cluster.robotics", "intelligent_systems"),
    ("moveit", "MoveIt", "MoveIt", "MoveIt2|运动规划", "ros", "cluster.robotics", "intelligent_systems"),
    ("nav2", "Nav2", "Nav2", "ROS 2导航", "ros2", "cluster.robotics", "intelligent_systems"),
    ("urdf", "URDF", "URDF", "Unified Robot Description Format", "ros", "cluster.robotics", "intelligent_systems"),
    ("tf2", "tf2", "tf2", "坐标变换", "ros", "cluster.robotics", "intelligent_systems"),
    ("abb-robot", "ABB机器人", "ABB Robotics", "ABB工业机器人", "", "cluster.robotics", "intelligent_systems"),
    ("kuka", "KUKA", "KUKA", "库卡机器人", "", "cluster.robotics", "intelligent_systems"),
    ("fanuc", "FANUC", "FANUC", "发那科", "", "cluster.robotics", "intelligent_systems"),
    ("yaskawa", "安川", "Yaskawa", "Yaskawa Motoman", "", "cluster.robotics", "intelligent_systems"),
    ("universal-robots", "优傲", "Universal Robots", "UR协作机器人|UR5", "", "cluster.robotics", "intelligent_systems"),
    ("cobot", "协作机器人", "Collaborative Robot", "人机协作", "", "cluster.robotics", "intelligent_systems"),
    ("slam", "SLAM", "SLAM", "同时定位与地图构建", "", "cluster.robotics", "intelligent_systems"),
    ("path-planning", "路径规划", "Path Planning", "A*|RRT", "", "cluster.robotics", "intelligent_systems"),
    ("inverse-kinematics", "逆运动学", "Inverse Kinematics", "IK", "", "cluster.robotics", "intelligent_systems"),
    ("pid-control", "PID控制", "PID Control", "比例积分微分", "", "cluster.robotics", "intelligent_systems"),
    ("impedance-control", "阻抗控制", "Impedance Control", "力控", "", "cluster.robotics", "intelligent_systems"),
    ("hand-eye-calib", "手眼标定", "Hand-Eye Calibration", "眼在手上", "", "cluster.robotics", "intelligent_systems"),
    ("grasp-planning", "抓取规划", "Grasp Planning", "抓取姿态", "", "cluster.robotics", "intelligent_systems"),
    ("embodied-ai", "具身智能", "Embodied AI", "具身智能机器人", "", "cluster.robotics", "intelligent_systems"),
    ("teleoperation", "遥操作", "Teleoperation", "远程操控", "", "cluster.robotics", "intelligent_systems"),
    ("plc", "PLC", "PLC", "可编程逻辑控制器", "", "cluster.industrial", "intelligent_systems"),
    ("siemens-plc", "西门子PLC", "Siemens PLC", "S7-1200|S7-1500|TIA Portal", "plc", "cluster.industrial", "intelligent_systems"),
    ("mitsubishi-plc", "三菱PLC", "Mitsubishi PLC", "FX|Q系列", "plc", "cluster.industrial", "intelligent_systems"),
    ("omron-plc", "欧姆龙PLC", "Omron PLC", "欧姆龙", "plc", "cluster.industrial", "intelligent_systems"),
    ("codesys", "CODESYS", "CODESYS", "IEC 61131", "plc", "cluster.industrial", "intelligent_systems"),
    ("twincat", "TwinCAT", "TwinCAT", "Beckhoff TwinCAT", "", "cluster.industrial", "intelligent_systems"),
    ("scada", "SCADA", "SCADA", "数据采集与监视控制", "", "cluster.industrial", "intelligent_systems"),
    ("opcua", "OPC UA", "OPC UA", "OPC Unified Architecture", "", "cluster.industrial", "intelligent_systems"),
    ("ethercat", "EtherCAT", "EtherCAT", "以太网控制自动化", "", "cluster.industrial", "intelligent_systems"),
    ("modbus", "Modbus", "Modbus", "Modbus TCP|RTU", "", "cluster.industrial", "intelligent_systems"),
    ("profinet", "PROFINET", "PROFINET", "工业以太网PROFINET", "", "cluster.industrial", "intelligent_systems"),
    ("can-bus", "CAN总线", "CAN", "Controller Area Network", "", "cluster.industrial", "intelligent_systems"),
    ("mes", "MES", "MES", "制造执行系统", "", "cluster.industrial", "intelligent_systems"),
    ("mom", "MOM", "Manufacturing Operations Management", "制造运营管理", "", "cluster.industrial", "intelligent_systems"),
    ("aps", "APS", "APS", "高级计划排程", "", "cluster.industrial", "intelligent_systems"),
    ("erp", "ERP", "ERP", "企业资源计划", "", "cluster.industrial", "intelligent_systems"),
    ("sap", "SAP", "SAP", "SAP ERP|SAP S/4HANA", "erp", "cluster.industrial", "intelligent_systems"),
    ("cnc", "数控", "CNC", "计算机数控", "", "cluster.industrial", "intelligent_systems"),
    ("cam", "CAM", "CAM", "计算机辅助制造", "", "cluster.industrial", "intelligent_systems"),
    ("cad", "CAD", "CAD", "计算机辅助设计", "", "cluster.industrial", "intelligent_systems"),
    ("solidworks", "SolidWorks", "SolidWorks", "Dassault SolidWorks", "cad", "cluster.industrial", "intelligent_systems"),
    ("catia", "CATIA", "CATIA", "Dassault CATIA", "cad", "cluster.industrial", "intelligent_systems"),
    ("autocad", "AutoCAD", "AutoCAD", "Autodesk AutoCAD", "cad", "cluster.industrial", "intelligent_systems"),
    ("ug-nx", "UG NX", "Siemens NX", "Unigraphics", "cad", "cluster.industrial", "intelligent_systems"),
    ("creo", "Creo", "Creo", "Pro/E|PTC Creo", "cad", "cluster.industrial", "intelligent_systems"),
    ("labview", "LabVIEW", "LabVIEW", "NI LabVIEW", "", "cluster.industrial", "intelligent_systems"),
    ("simulink", "Simulink", "Simulink", "MATLAB Simulink", "matlab", "cluster.industrial", "intelligent_systems"),
    ("modelica", "Modelica", "Modelica", "多领域仿真", "", "cluster.industrial", "intelligent_systems"),
    ("iec61131", "IEC 61131-3", "IEC 61131-3", "PLC编程语言标准", "plc", "cluster.industrial", "intelligent_systems"),
    ("industrial-ethernet", "工业以太网", "Industrial Ethernet", "工业网络", "", "cluster.industrial", "intelligent_systems"),
    ("iiot", "工业物联网", "IIoT", "Industrial IoT", "", "cluster.industrial", "intelligent_systems"),
    ("stm32", "STM32", "STM32", "意法半导体MCU", "", "cluster.embedded", "intelligent_systems"),
    ("freertos", "FreeRTOS", "FreeRTOS", "实时操作系统FreeRTOS", "", "cluster.embedded", "intelligent_systems"),
    ("zephyr", "Zephyr", "Zephyr RTOS", "Linux基金会Zephyr", "", "cluster.embedded", "intelligent_systems"),
    ("qnx", "QNX", "QNX", "黑莓QNX", "", "cluster.embedded", "intelligent_systems"),
    ("vxworks", "VxWorks", "VxWorks", "风河VxWorks", "", "cluster.embedded", "intelligent_systems"),
    ("rt-thread", "RT-Thread", "RT-Thread", "国产RTOS", "", "cluster.embedded", "intelligent_systems"),
    ("arm-mcu", "ARM Cortex-M", "ARM Cortex-M", "Cortex-M4|M7", "", "cluster.embedded", "intelligent_systems"),
    ("risc-v", "RISC-V", "RISC-V", "开源指令集", "", "cluster.embedded", "intelligent_systems"),
    ("fpga", "FPGA", "FPGA", "现场可编程门阵列", "", "cluster.embedded", "intelligent_systems"),
    ("verilog", "Verilog", "Verilog", "Verilog HDL", "fpga", "cluster.eda", "intelligent_systems"),
    ("vhdl", "VHDL", "VHDL", "VHSIC HDL", "fpga", "cluster.eda", "intelligent_systems"),
    ("systemverilog", "SystemVerilog", "SystemVerilog", "SV验证", "verilog", "cluster.eda", "intelligent_systems"),
    ("embedded-linux", "嵌入式Linux", "Embedded Linux", "Yocto|Buildroot", "linux", "cluster.embedded", "intelligent_systems"),
    ("yocto", "Yocto", "Yocto Project", "Yocto构建", "embedded-linux", "cluster.embedded", "intelligent_systems"),
    ("buildroot", "Buildroot", "Buildroot", "嵌入式构建", "embedded-linux", "cluster.embedded", "intelligent_systems"),
    ("uboot", "U-Boot", "U-Boot", "引导加载程序", "embedded-linux", "cluster.embedded", "intelligent_systems"),
    ("device-tree", "设备树", "Device Tree", "DTS|DTB", "embedded-linux", "cluster.embedded", "intelligent_systems"),
    ("i2c", "I2C", "I2C", "I²C总线", "", "cluster.embedded", "intelligent_systems"),
    ("spi", "SPI", "SPI", "串行外设接口", "", "cluster.embedded", "intelligent_systems"),
    ("uart", "UART", "UART", "串口", "", "cluster.embedded", "intelligent_systems"),
    ("dma", "DMA", "DMA", "直接内存访问", "", "cluster.embedded", "intelligent_systems"),
    ("digital-twin", "数字孪生", "Digital Twin", "数字双胞胎", "", "cluster.digital-twin", "intelligent_systems"),
    ("unity", "Unity", "Unity", "Unity3D|Unity引擎", "", "cluster.digital-twin", "intelligent_systems"),
    ("unreal", "Unreal Engine", "Unreal Engine", "UE5|虚幻引擎", "", "cluster.digital-twin", "intelligent_systems"),
    ("nvidia-omniverse", "Omniverse", "NVIDIA Omniverse", "Omniverse数字孪生", "", "cluster.digital-twin", "intelligent_systems"),
    ("bentley-itwin", "iTwin", "Bentley iTwin", "基础设施孪生", "", "cluster.digital-twin", "intelligent_systems"),
    ("bim", "BIM", "BIM", "建筑信息模型", "", "cluster.digital-twin", "intelligent_systems"),
    ("revit", "Revit", "Autodesk Revit", "BIM Revit", "bim", "cluster.digital-twin", "intelligent_systems"),
    ("ifcopenshell", "IFC", "IFC", "Industry Foundation Classes", "bim", "cluster.digital-twin", "intelligent_systems"),
    ("ansys", "ANSYS", "ANSYS", "有限元ANSYS", "", "cluster.digital-twin", "intelligent_systems"),
    ("abaqus", "Abaqus", "Abaqus", "达索Abaqus", "", "cluster.digital-twin", "intelligent_systems"),
    ("adams", "ADAMS", "ADAMS", "多体动力学", "", "cluster.digital-twin", "intelligent_systems"),
    ("vr", "虚拟现实", "Virtual Reality", "VR", "", "cluster.vr-ar", "intelligent_systems"),
    ("ar", "增强现实", "Augmented Reality", "AR", "", "cluster.vr-ar", "intelligent_systems"),
    ("mr", "混合现实", "Mixed Reality", "MR|XR", "", "cluster.vr-ar", "intelligent_systems"),
    ("openxr", "OpenXR", "OpenXR", "XR开放标准", "", "cluster.vr-ar", "intelligent_systems"),
    ("webxr", "WebXR", "WebXR", "浏览器XR", "", "cluster.vr-ar", "intelligent_systems"),
    ("pico-sdk", "PICO SDK", "PICO SDK", "字节PICO", "", "cluster.vr-ar", "intelligent_systems"),
    ("quest-sdk", "Meta Quest", "Meta Quest SDK", "Oculus", "", "cluster.vr-ar", "intelligent_systems"),
    ("arkit", "ARKit", "ARKit", "Apple ARKit", "ar", "cluster.vr-ar", "intelligent_systems"),
    ("arcore", "ARCore", "ARCore", "Google ARCore", "ar", "cluster.vr-ar", "intelligent_systems"),
    ("eda", "电子设计自动化", "EDA", "IC设计工具", "", "cluster.eda", "intelligent_systems"),
    ("vivado", "Vivado", "Xilinx Vivado", "AMD Vivado", "fpga", "cluster.eda", "intelligent_systems"),
    ("quartus", "Quartus", "Intel Quartus", "Altera Quartus", "fpga", "cluster.eda", "intelligent_systems"),
    ("synopsys-dve", "Synopsys", "Synopsys", "VCS|Design Compiler", "eda", "cluster.eda", "intelligent_systems"),
    ("cadence", "Cadence", "Cadence", "Virtuoso|Innovus", "eda", "cluster.eda", "intelligent_systems"),
    ("mentor", "Siemens EDA", "Siemens EDA", "Mentor Graphics", "eda", "cluster.eda", "intelligent_systems"),
    ("spice", "SPICE", "SPICE", "电路仿真SPICE", "eda", "cluster.eda", "intelligent_systems"),
    ("pcb", "PCB设计", "PCB Design", "印刷电路板", "", "cluster.eda", "intelligent_systems"),
    ("altium", "Altium Designer", "Altium Designer", "AD", "pcb", "cluster.eda", "intelligent_systems"),
    ("kicad", "KiCad", "KiCad", "开源EDA", "pcb", "cluster.eda", "intelligent_systems"),
    ("autosar", "AUTOSAR", "AUTOSAR", "汽车开放系统架构", "", "cluster.vehicle", "intelligent_systems"),
    ("canfd", "CAN FD", "CAN FD", "灵活数据率CAN", "can-bus", "cluster.vehicle", "intelligent_systems"),
    ("someip", "SOME/IP", "SOME/IP", "车载以太网", "", "cluster.vehicle", "intelligent_systems"),
    ("ros-automotive", "自动驾驶中间件", "Autonomous Driving Stack", "Apollo|Autoware", "", "cluster.vehicle", "intelligent_systems"),
    ("apollo", "Apollo", "Baidu Apollo", "百度Apollo", "ros-automotive", "cluster.vehicle", "intelligent_systems"),
    ("autoware", "Autoware", "Autoware", "开源自动驾驶", "ros-automotive", "cluster.vehicle", "intelligent_systems"),
    ("adas", "ADAS", "ADAS", "高级驾驶辅助", "", "cluster.vehicle", "intelligent_systems"),
    ("car-ethernet", "车载以太网", "Automotive Ethernet", "100BASE-T1", "", "cluster.vehicle", "intelligent_systems"),
]

IOT = [
    ("mqtt", "MQTT", "MQTT", "Message Queuing Telemetry Transport", "", "cluster.iot-protocol", "iot"),
    ("coap", "CoAP", "CoAP", "Constrained Application Protocol", "", "cluster.iot-protocol", "iot"),
    ("lwm2m", "LwM2M", "LwM2M", "Lightweight M2M", "", "cluster.iot-protocol", "iot"),
    ("amqp", "AMQP", "AMQP", "Advanced Message Queuing Protocol", "", "cluster.iot-protocol", "iot"),
    ("http", "HTTP", "HTTP", "HTTPS|HTTP/2", "", "cluster.iot-protocol", "iot"),
    ("websocket", "WebSocket", "WebSocket", "WS协议", "", "cluster.iot-protocol", "iot"),
    ("grpc", "gRPC", "gRPC", "Google RPC", "", "cluster.iot-protocol", "iot"),
    ("protobuf", "Protocol Buffers", "Protocol Buffers", "protobuf|proto3", "", "cluster.iot-protocol", "iot"),
    ("dds", "DDS", "DDS", "Data Distribution Service", "", "cluster.iot-protocol", "iot"),
    ("sparkplug", "Sparkplug", "Sparkplug B", "MQTT Sparkplug", "mqtt", "cluster.iot-protocol", "iot"),
    ("zigbee", "Zigbee", "Zigbee", "紫蜂", "", "cluster.iot-wireless", "iot"),
    ("ble", "蓝牙低功耗", "Bluetooth Low Energy", "BLE|Bluetooth LE", "", "cluster.iot-wireless", "iot"),
    ("lorawan", "LoRaWAN", "LoRaWAN", "LoRa", "", "cluster.iot-wireless", "iot"),
    ("nbiot", "NB-IoT", "NB-IoT", "窄带物联网", "", "cluster.iot-wireless", "iot"),
    ("lte-m", "LTE-M", "LTE-M", "Cat-M1", "", "cluster.iot-wireless", "iot"),
    ("5g", "5G", "5G", "第五代移动通信|NR", "", "cluster.iot-wireless", "iot"),
    ("wifi", "Wi-Fi", "Wi-Fi", "WiFi|IEEE 802.11", "", "cluster.iot-wireless", "iot"),
    ("thread-net", "Thread", "Thread", "Thread组网", "", "cluster.iot-wireless", "iot"),
    ("matter", "Matter", "Matter", "CSA Matter|原CHIP", "", "cluster.iot-wireless", "iot"),
    ("zwave", "Z-Wave", "Z-Wave", "ZWave", "", "cluster.iot-wireless", "iot"),
    ("rfid", "RFID", "RFID", "射频识别", "", "cluster.iot-wireless", "iot"),
    ("nfc", "NFC", "NFC", "近场通信", "", "cluster.iot-wireless", "iot"),
    ("uwb", "UWB", "Ultra-Wideband", "超宽带定位", "", "cluster.iot-wireless", "iot"),
    ("sigfox", "Sigfox", "Sigfox", "低功耗广域", "", "cluster.iot-wireless", "iot"),
    ("wpan", "无线个域网", "WPAN", "IEEE 802.15.4", "", "cluster.iot-wireless", "iot"),
    ("6lowpan", "6LoWPAN", "6LoWPAN", "IPv6 over Low-Power WPAN", "", "cluster.iot-wireless", "iot"),
    # ESP8266 是另一颗芯片，不是 ESP32 的别名；要收就该单独立技能点。
    ("esp32", "ESP32", "ESP32", "乐鑫ESP32", "", "cluster.iot-hw", "iot"),
    ("raspberry-pi", "树莓派", "Raspberry Pi", "RPi|树莓派", "", "cluster.iot-hw", "iot"),
    ("arduino", "Arduino", "Arduino", "Arduino IDE", "", "cluster.iot-hw", "iot"),
    ("nrf52", "nRF52", "nRF52", "Nordic nRF52840", "", "cluster.iot-hw", "iot"),
    ("stm32-iot", "STM32物联网", "STM32 IoT", "STM32WL|STM32WB", "stm32", "cluster.iot-hw", "iot"),
    ("sensor-fusion", "传感器融合", "Sensor Fusion", "多传感器融合", "", "cluster.iot-hw", "iot"),
    ("imu", "惯性测量单元", "IMU", "加速度计陀螺仪", "", "cluster.iot-hw", "iot"),
    ("mems", "MEMS传感器", "MEMS", "微机电系统", "", "cluster.iot-hw", "iot"),
    ("gateway", "物联网网关", "IoT Gateway", "边缘网关", "", "cluster.iot-hw", "iot"),
    ("modbus-iot", "Modbus采集", "Modbus Acquisition", "工控采集", "modbus", "cluster.iot-hw", "iot"),
    ("aws-iot", "AWS IoT", "AWS IoT Core", "亚马逊物联网", "aws", "cluster.iot-platform", "iot"),
    ("azure-iot", "Azure IoT", "Azure IoT Hub", "微软物联网", "azure", "cluster.iot-platform", "iot"),
    ("aliyun-iot", "阿里云物联网", "Alibaba Cloud IoT", "IoT平台阿里云", "aliyun", "cluster.iot-platform", "iot"),
    ("thingsboard", "ThingsBoard", "ThingsBoard", "开源物联网平台", "", "cluster.iot-platform", "iot"),
    ("emqx", "EMQX", "EMQX", "Erlang MQTT Broker", "mqtt", "cluster.iot-platform", "iot"),
    ("hivemq", "HiveMQ", "HiveMQ", "企业MQTT", "mqtt", "cluster.iot-platform", "iot"),
    ("mosquitto", "Mosquitto", "Eclipse Mosquitto", "mosquitto代理", "mqtt", "cluster.iot-platform", "iot"),
    ("chirpstack", "ChirpStack", "ChirpStack", "LoRaWAN网络服务器", "lorawan", "cluster.iot-platform", "iot"),
    ("home-assistant", "Home Assistant", "Home Assistant", "HA智能家居", "", "cluster.iot-platform", "iot"),
    ("openhab", "openHAB", "openHAB", "开源智能家居", "", "cluster.iot-platform", "iot"),
    ("node-red", "Node-RED", "Node-RED", "流编程物联网", "", "cluster.iot-platform", "iot"),
    ("thingspeak", "ThingSpeak", "ThingSpeak", "MathWorks IoT", "", "cluster.iot-platform", "iot"),
    ("kubesense", "设备管理", "Device Management", "物模型|设备影子", "", "cluster.iot-platform", "iot"),
    ("digital-shadow", "设备影子", "Device Shadow", "影子设备", "kubesense", "cluster.iot-platform", "iot"),
    ("ota", "空中升级", "OTA", "Over-the-Air Update", "", "cluster.iot-platform", "iot"),
    ("edge-computing", "边缘计算", "Edge Computing", "边侧计算", "", "cluster.edge", "iot"),
    ("kubeedge", "KubeEdge", "KubeEdge", "云原生边缘", "kubernetes", "cluster.edge", "iot"),
    ("openyurt", "OpenYurt", "OpenYurt", "阿里OpenYurt", "kubernetes", "cluster.edge", "iot"),
    ("k3s", "K3s", "K3s", "轻量Kubernetes", "kubernetes", "cluster.edge", "iot"),
    ("edgex", "EdgeX Foundry", "EdgeX Foundry", "Linux基金会边缘", "", "cluster.edge", "iot"),
    ("openness", "OpenNESS", "OpenNESS", "Intel边缘", "", "cluster.edge", "iot"),
    ("aws-greengrass", "AWS IoT Greengrass", "AWS IoT Greengrass", "Greengrass", "aws-iot", "cluster.edge", "iot"),
    ("azure-iot-edge", "Azure IoT Edge", "Azure IoT Edge", "微软边缘", "azure-iot", "cluster.edge", "iot"),
    ("nvidia-jetson", "Jetson", "NVIDIA Jetson", "Jetson Nano|Orin", "", "cluster.edge", "iot"),
    ("intel-nuc", "边缘工控机", "Industrial PC", "工控机|IPC", "", "cluster.edge", "iot"),
    ("tinyml", "TinyML", "TinyML", "端侧机器学习", "", "cluster.edge", "iot"),
    ("tflite-micro", "TensorFlow Lite Micro", "TensorFlow Lite Micro", "TFLM", "tinyml", "cluster.edge", "iot"),
    ("iot-security", "物联网安全", "IoT Security", "设备安全", "", "cluster.iot-security", "iot"),
    ("pki", "公钥基础设施", "PKI", "证书体系", "iot-security", "cluster.iot-security", "iot"),
    ("dtls", "DTLS", "DTLS", "Datagram TLS", "iot-security", "cluster.iot-security", "iot"),
    ("tpm", "可信平台模块", "TPM", "Trusted Platform Module", "iot-security", "cluster.iot-security", "iot"),
    ("secure-boot", "安全启动", "Secure Boot", "secureboot", "iot-security", "cluster.iot-security", "iot"),
    ("firmware-analysis", "固件分析", "Firmware Analysis", "固件安全", "iot-security", "cluster.iot-security", "iot"),
    ("iec62443", "IEC 62443", "IEC 62443", "工控安全标准", "iot-security", "cluster.iot-security", "iot"),
    ("mqtt-tls", "MQTT over TLS", "MQTT over TLS", "加密MQTT", "mqtt", "cluster.iot-security", "iot"),
    ("zero-trust-iot", "零信任物联网", "Zero Trust IoT", "设备零信任", "iot-security", "cluster.iot-security", "iot"),
    ("sbom", "软件物料清单", "SBOM", "Software Bill of Materials", "iot-security", "cluster.iot-security", "iot"),
    ("opcua-security", "OPC UA安全", "OPC UA Security", "工控认证加密", "opcua", "cluster.iot-security", "iot"),
    ("lorawan-join", "LoRaWAN入网", "LoRaWAN Join", "OTAA|ABP", "lorawan", "cluster.iot-wireless", "iot"),
    ("ble-mesh", "蓝牙Mesh", "Bluetooth Mesh", "BLE Mesh", "ble", "cluster.iot-wireless", "iot"),
    ("wifi-halow", "Wi-Fi HaLow", "Wi-Fi HaLow", "IEEE 802.11ah", "wifi", "cluster.iot-wireless", "iot"),
    ("redcap", "5G RedCap", "5G RedCap", "轻量化5G", "5g", "cluster.iot-wireless", "iot"),
    ("tsn", "时间敏感网络", "TSN", "Time-Sensitive Networking", "", "cluster.iot-wireless", "iot"),
    ("micropython", "MicroPython", "MicroPython", "微Python", "python", "cluster.iot-hw", "iot"),
    ("circuitpython", "CircuitPython", "CircuitPython", "Adafruit CircuitPython", "python", "cluster.iot-hw", "iot"),
    ("platformio", "PlatformIO", "PlatformIO", "嵌入式IDE", "", "cluster.iot-hw", "iot"),
    ("esphome", "ESPHome", "ESPHome", "Home Assistant固件", "esp32", "cluster.iot-hw", "iot"),
    ("tasmota", "Tasmota", "Tasmota", "开源固件", "esp32", "cluster.iot-hw", "iot"),
]
