"""技能点编目：一行一条。id 由 slug 稳定生成，例如 pytorch → skill.pytorch。

字段: slug, name_zh, name_en, extra_aliases, parent_slug, cluster_id, direction

extra_aliases 用 | 分隔，不要放单字母或动词歧义面（Go/R/C 的消歧在 build.py）。
parent_slug 空字符串表示无上位技能点。
"""

# fmt: off
AI = [
    # --- 编程语言 ---
    ("python", "Python", "Python", "py|蟒蛇语言", "", "cluster.prog-lang", "ai"),
    ("java", "Java", "Java", "Java语言|JDK", "", "cluster.prog-lang", "ai"),
    ("javascript", "JavaScript", "JavaScript", "JS|ECMAScript", "", "cluster.prog-lang", "ai"),
    ("typescript", "TypeScript", "TypeScript", "TS", "", "cluster.prog-lang", "ai"),
    ("golang", "Go语言", "Go", "Golang|Go 语言", "", "cluster.prog-lang", "ai"),
    ("rust", "Rust", "Rust", "Rust语言", "", "cluster.prog-lang", "ai"),
    ("cpp", "C++", "C++", "CPP|cplusplus|现代C++", "", "cluster.prog-lang", "ai"),
    ("c-lang", "C语言", "C", "ISO C|C99|C11", "", "cluster.prog-lang", "ai"),
    ("csharp", "C#", "C#", "CSharp|Csharp|.NET C#", "", "cluster.prog-lang", "ai"),
    ("kotlin", "Kotlin", "Kotlin", "Kotlin语言", "", "cluster.prog-lang", "ai"),
    ("swift", "Swift", "Swift", "Swift语言", "", "cluster.prog-lang", "ai"),
    ("scala", "Scala", "Scala", "Scala语言", "", "cluster.prog-lang", "ai"),
    ("ruby", "Ruby", "Ruby", "Ruby语言", "", "cluster.prog-lang", "ai"),
    ("php", "PHP", "PHP", "PHP语言", "", "cluster.prog-lang", "ai"),
    ("r-lang", "R语言", "R", "GNU R|R language", "", "cluster.prog-lang", "ai"),
    ("matlab", "MATLAB", "MATLAB", "Matlab|The MathWorks MATLAB", "", "cluster.prog-lang", "ai"),
    ("julia", "Julia", "Julia", "Julia语言", "", "cluster.prog-lang", "ai"),
    ("lua", "Lua", "Lua", "Lua语言", "", "cluster.prog-lang", "ai"),
    ("perl", "Perl", "Perl", "Perl语言", "", "cluster.prog-lang", "ai"),
    ("haskell", "Haskell", "Haskell", "Haskell语言", "", "cluster.prog-lang", "ai"),
    ("dart", "Dart", "Dart", "Dart语言", "", "cluster.prog-lang", "ai"),
    ("objc", "Objective-C", "Objective-C", "ObjC|OC语言", "", "cluster.prog-lang", "ai"),
    ("bash", "Bash", "Bash", "bash脚本|Shell脚本", "", "cluster.prog-lang", "ai"),
    ("powershell", "PowerShell", "PowerShell", "pwsh", "", "cluster.prog-lang", "ai"),
    ("sql", "SQL", "SQL", "结构化查询语言|Structured query language SQL", "", "cluster.prog-lang", "ai"),
    ("html", "HTML", "HTML", "超文本标记语言|HTML5", "", "cluster.prog-lang", "ai"),
    ("css", "CSS", "CSS", "层叠样式表|CSS3", "", "cluster.prog-lang", "ai"),
    ("solidity", "Solidity", "Solidity", "Solidity语言", "", "cluster.prog-lang", "ai"),
    ("cuda-c", "CUDA C++", "CUDA C++", "CUDA编程", "", "cluster.prog-lang", "ai"),
    ("fortran", "Fortran", "Fortran", "FORTRAN", "", "cluster.prog-lang", "ai"),
    ("groovy", "Groovy", "Groovy", "Groovy语言", "", "cluster.prog-lang", "ai"),
    ("wasm", "WebAssembly", "WebAssembly", "WASM|Wasm", "", "cluster.prog-lang", "ai"),
    ("assembly", "汇编语言", "Assembly", "ASM|汇编", "", "cluster.prog-lang", "ai"),
    ("elixir", "Elixir", "Elixir", "Elixir语言", "", "cluster.prog-lang", "ai"),
    ("erlang", "Erlang", "Erlang", "Erlang语言", "", "cluster.prog-lang", "ai"),
    ("ocaml", "OCaml", "OCaml", "Ocaml", "", "cluster.prog-lang", "ai"),
    ("fsharp", "F#", "F#", "FSharp", "", "cluster.prog-lang", "ai"),
    ("zig", "Zig", "Zig", "Zig语言", "", "cluster.prog-lang", "ai"),
    ("nim", "Nim", "Nim", "Nim语言", "", "cluster.prog-lang", "ai"),
    ("clojure", "Clojure", "Clojure", "Clojure语言", "", "cluster.prog-lang", "ai"),
    # --- 机器学习框架 ---
    ("deep-learning", "深度学习", "Deep Learning", "DL|深度神经网络", "", "cluster.ml-framework", "ai"),
    ("machine-learning", "机器学习", "Machine Learning", "ML", "", "cluster.ml-framework", "ai"),
    ("pytorch", "PyTorch", "PyTorch", "pytorch|torch", "deep-learning", "cluster.ml-framework", "ai"),
    ("tensorflow", "TensorFlow", "TensorFlow", "TF|tensorflow", "deep-learning", "cluster.ml-framework", "ai"),
    ("keras", "Keras", "Keras", "tf.keras", "tensorflow", "cluster.ml-framework", "ai"),
    ("jax", "JAX", "JAX", "google jax", "deep-learning", "cluster.ml-framework", "ai"),
    ("flax", "Flax", "Flax", "flax.linen", "jax", "cluster.ml-framework", "ai"),
    ("scikit-learn", "scikit-learn", "scikit-learn", "sklearn|Scikit-Learn", "machine-learning", "cluster.ml-framework", "ai"),
    ("mxnet", "MXNet", "MXNet", "Apache MXNet", "deep-learning", "cluster.ml-framework", "ai"),
    ("paddlepaddle", "飞桨", "PaddlePaddle", "Paddle|百度飞桨", "deep-learning", "cluster.ml-framework", "ai"),
    ("mindspore", "昇思MindSpore", "MindSpore", "MindSpore|昇思", "deep-learning", "cluster.ml-framework", "ai"),
    ("onnx", "ONNX", "ONNX", "Open Neural Network Exchange", "deep-learning", "cluster.ml-framework", "ai"),
    ("huggingface-transformers", "Transformers库", "Hugging Face Transformers", "transformers|HF Transformers", "deep-learning", "cluster.ml-framework", "ai"),
    ("lightning", "PyTorch Lightning", "PyTorch Lightning", "Lightning|pytorch-lightning", "pytorch", "cluster.ml-framework", "ai"),
    ("fastai", "fastai", "fastai", "FastAI", "pytorch", "cluster.ml-framework", "ai"),
    ("xgboost", "XGBoost", "XGBoost", "xgb", "machine-learning", "cluster.ml-framework", "ai"),
    ("lightgbm", "LightGBM", "LightGBM", "LGBM", "machine-learning", "cluster.ml-framework", "ai"),
    ("catboost", "CatBoost", "CatBoost", "Yandex CatBoost", "machine-learning", "cluster.ml-framework", "ai"),
    ("rapids", "RAPIDS", "RAPIDS", "cuDF|cuML", "machine-learning", "cluster.ml-framework", "ai"),
    ("mlxtend", "mlxtend", "mlxtend", "machine learning extensions", "machine-learning", "cluster.ml-framework", "ai"),
    ("skorch", "skorch", "skorch", "sklearn pytorch", "pytorch", "cluster.ml-framework", "ai"),
    ("ignite", "PyTorch Ignite", "PyTorch Ignite", "ignite", "pytorch", "cluster.ml-framework", "ai"),
    ("detectron-none", "占位勿用", "x", "", "", "cluster.ml-framework", "ai"),
]

# 上面最后一条会在 loader 里丢掉。真正的视觉库写在后面。
AI = [r for r in AI if r[0] != "detectron-none"]

AI += [
    ("openmmlab", "OpenMMLab", "OpenMMLab", "MMLab", "deep-learning", "cluster.cv", "ai"),
    # --- 大模型与生成式 AI ---
    ("llm", "大模型", "Large Language Model", "LLM|大型语言模型|大语言模型", "", "cluster.llm-genai", "ai"),
    ("generative-ai", "生成式人工智能", "Generative AI", "GenAI|生成式AI|AIGC", "", "cluster.llm-genai", "ai"),
    ("gpt", "GPT", "GPT", "Generative Pre-trained Transformer", "llm", "cluster.llm-genai", "ai"),
    ("bert", "BERT", "BERT", "Bidirectional Encoder Representations from Transformers", "llm", "cluster.llm-genai", "ai"),
    ("t5", "T5", "T5", "Text-to-Text Transfer Transformer", "llm", "cluster.llm-genai", "ai"),
    ("llama", "LLaMA", "LLaMA", "Llama|Meta Llama", "llm", "cluster.llm-genai", "ai"),
    ("qwen", "通义千问", "Qwen", "Qwen2|Qwen2.5|Qwen3|阿里千问", "llm", "cluster.llm-genai", "ai"),
    ("chatglm", "ChatGLM", "ChatGLM", "智谱GLM|GLM-4|ChatGLM3", "llm", "cluster.llm-genai", "ai"),
    ("baichuan", "百川", "Baichuan", "Baichuan2|百川智能", "llm", "cluster.llm-genai", "ai"),
    ("deepseek", "DeepSeek", "DeepSeek", "深度求索|DeepSeek-V3|DeepSeek-R1", "llm", "cluster.llm-genai", "ai"),
    ("yi-model", "零一万物Yi", "Yi", "Yi-34B|01.AI", "llm", "cluster.llm-genai", "ai"),
    ("internlm", "书生浦语", "InternLM", "InternLM2|上海AI实验室", "llm", "cluster.llm-genai", "ai"),
    ("minimax-model", "MiniMax", "MiniMax", "abab", "llm", "cluster.llm-genai", "ai"),
    ("doubao", "豆包大模型", "Doubao", "字节豆包|Seed", "llm", "cluster.llm-genai", "ai"),
    ("ernie", "文心一言", "ERNIE", "文心大模型|ERNIE Bot", "llm", "cluster.llm-genai", "ai"),
    ("sparkdesk", "讯飞星火", "SparkDesk", "星火大模型", "llm", "cluster.llm-genai", "ai"),
    ("hunyuan", "混元", "Hunyuan", "腾讯混元", "llm", "cluster.llm-genai", "ai"),
    ("gemini", "Gemini", "Gemini", "Google Gemini|Bard", "llm", "cluster.llm-genai", "ai"),
    ("claude-api", "Claude", "Claude", "Anthropic Claude|Claude API", "llm", "cluster.llm-genai", "ai"),
    ("openai-api", "OpenAI API", "OpenAI API", "ChatGPT API|openai sdk", "llm", "cluster.llm-genai", "ai"),
    ("mistral", "Mistral", "Mistral", "Mixtral|Mistral AI", "llm", "cluster.llm-genai", "ai"),
    ("gemma", "Gemma", "Gemma", "Google Gemma", "llm", "cluster.llm-genai", "ai"),
    ("phi-model", "Phi", "Phi", "Phi-3|Phi-4|Microsoft Phi", "llm", "cluster.llm-genai", "ai"),
    ("prompt-engineering", "提示词工程", "Prompt Engineering", "提示工程|Prompt", "llm", "cluster.llm-genai", "ai"),
    ("rag", "检索增强生成", "Retrieval-Augmented Generation", "RAG|检索增强", "llm", "cluster.llm-genai", "ai"),
    ("lora", "LoRA", "LoRA", "Low-Rank Adaptation|低秩适应", "llm", "cluster.llm-genai", "ai"),
    ("qlora", "QLoRA", "QLoRA", "量化LoRA", "lora", "cluster.llm-genai", "ai"),
    ("sft", "监督微调", "Supervised Fine-Tuning", "SFT|指令微调", "llm", "cluster.llm-genai", "ai"),
    ("rlhf", "人类反馈强化学习", "RLHF", "Reinforcement Learning from Human Feedback", "llm", "cluster.llm-genai", "ai"),
    ("dpo", "直接偏好优化", "DPO", "Direct Preference Optimization", "llm", "cluster.llm-genai", "ai"),
    ("grpo", "GRPO", "GRPO", "Group Relative Policy Optimization", "llm", "cluster.llm-genai", "ai"),
    ("moe", "混合专家", "Mixture of Experts", "MoE|稀疏专家", "llm", "cluster.llm-genai", "ai"),
    ("tokenizer", "分词器", "Tokenizer", "tokenization|BPE分词", "llm", "cluster.llm-genai", "ai"),
    ("context-window", "上下文窗口", "Context Window", "context length|长上下文", "llm", "cluster.llm-genai", "ai"),
    ("kv-cache", "KV Cache", "KV Cache", "键值缓存|KV缓存", "llm", "cluster.llm-genai", "ai"),
    ("vllm", "vLLM", "vLLM", "vllm推理", "llm", "cluster.llm-genai", "ai"),
    ("tensorrt-llm", "TensorRT-LLM", "TensorRT-LLM", "trt-llm", "llm", "cluster.llm-genai", "ai"),
    ("llamacpp", "llama.cpp", "llama.cpp", "llama cpp", "llm", "cluster.llm-genai", "ai"),
    ("ollama", "Ollama", "Ollama", "ollama本地部署", "llm", "cluster.llm-genai", "ai"),
    ("langchain", "LangChain", "LangChain", "langchainjs", "llm", "cluster.llm-genai", "ai"),
    ("llamaindex", "LlamaIndex", "LlamaIndex", "GPT Index", "llm", "cluster.llm-genai", "ai"),
    ("dify", "Dify", "Dify", "langgenius dify", "llm", "cluster.llm-genai", "ai"),
    ("fastgpt", "FastGPT", "FastGPT", "fastgpt知识库", "llm", "cluster.llm-genai", "ai"),
    ("semantic-kernel", "Semantic Kernel", "Semantic Kernel", "SK微软", "llm", "cluster.llm-genai", "ai"),
    ("haystack", "Haystack", "Haystack", "deepset Haystack", "llm", "cluster.llm-genai", "ai"),
    ("function-calling", "函数调用", "Function Calling", "tool calling|工具调用", "llm", "cluster.llm-genai", "ai"),
    ("mcp", "模型上下文协议", "Model Context Protocol", "MCP|Anthropic MCP", "llm", "cluster.llm-genai", "ai"),
    ("cot", "思维链", "Chain of Thought", "CoT|chain-of-thought", "prompt-engineering", "cluster.llm-genai", "ai"),
    ("react-prompt", "ReAct", "ReAct", "Reason+Act", "prompt-engineering", "cluster.llm-genai", "ai"),
    ("few-shot", "少样本学习", "Few-shot Learning", "few shot|in-context", "llm", "cluster.llm-genai", "ai"),
    ("embedding-model", "向量模型", "Embedding Model", "文本向量|text embedding", "llm", "cluster.llm-genai", "ai"),
    ("faiss", "Faiss", "Faiss", "Facebook AI Similarity Search", "embedding-model", "cluster.llm-genai", "ai"),
    ("milvus", "Milvus", "Milvus", "Zilliz|Milvus向量库", "embedding-model", "cluster.llm-genai", "ai"),
    ("qdrant", "Qdrant", "Qdrant", "Qdrant向量库", "embedding-model", "cluster.llm-genai", "ai"),
    ("chroma", "Chroma", "Chroma", "ChromaDB", "embedding-model", "cluster.llm-genai", "ai"),
    ("pinecone", "Pinecone", "Pinecone", "Pinecone向量库", "embedding-model", "cluster.llm-genai", "ai"),
    ("weaviate", "Weaviate", "Weaviate", "Weaviate向量库", "embedding-model", "cluster.llm-genai", "ai"),
    ("pgvector", "pgvector", "pgvector", "Postgres向量", "embedding-model", "cluster.llm-genai", "ai"),
    ("text2sql", "Text-to-SQL", "Text-to-SQL", "NL2SQL|自然语言转SQL", "llm", "cluster.llm-genai", "ai"),
    ("quantization", "模型量化", "Quantization", "INT8量化|权重量化", "llm", "cluster.llm-genai", "ai"),
    ("awq", "AWQ", "AWQ", "Activation-aware Weight Quantization", "quantization", "cluster.llm-genai", "ai"),
    ("gptq", "GPTQ", "GPTQ", "GPTQ量化", "quantization", "cluster.llm-genai", "ai"),
    ("gguf", "GGUF", "GGUF", "GGML|gguf格式", "llamacpp", "cluster.llm-genai", "ai"),
    ("peft", "PEFT", "PEFT", "Parameter-Efficient Fine-Tuning|参数高效微调", "lora", "cluster.llm-genai", "ai"),
    ("bitsandbytes", "bitsandbytes", "bitsandbytes", "bnb|8bit优化器", "quantization", "cluster.llm-genai", "ai"),
    ("deepspeed", "DeepSpeed", "DeepSpeed", "ZeRO|微软DeepSpeed", "llm", "cluster.llm-genai", "ai"),
    ("fsdp", "FSDP", "FSDP", "Fully Sharded Data Parallel", "pytorch", "cluster.llm-genai", "ai"),
    ("megatron", "Megatron-LM", "Megatron-LM", "Megatron|NVIDIA Megatron", "llm", "cluster.llm-genai", "ai"),
    ("colossalai", "Colossal-AI", "Colossal-AI", "ColossalAI", "llm", "cluster.llm-genai", "ai"),
    ("accelerate", "Accelerate", "Accelerate", "Hugging Face Accelerate", "huggingface-transformers", "cluster.llm-genai", "ai"),
    ("trl", "TRL", "TRL", "Transformer Reinforcement Learning", "huggingface-transformers", "cluster.llm-genai", "ai"),
    ("unsloth", "Unsloth", "Unsloth", "unsloth微调", "lora", "cluster.llm-genai", "ai"),
    ("llamafactory", "LLaMA-Factory", "LLaMA-Factory", "LlamaFactory", "sft", "cluster.llm-genai", "ai"),
    ("axolotl", "Axolotl", "Axolotl", "OpenAccess Axolotl", "sft", "cluster.llm-genai", "ai"),
    ("graph-rag", "GraphRAG", "GraphRAG", "图谱RAG", "rag", "cluster.llm-genai", "ai"),
    ("hyde", "HyDE", "HyDE", "Hypothetical Document Embeddings", "rag", "cluster.llm-genai", "ai"),
    ("flash-attention", "FlashAttention", "FlashAttention", "Flash Attention|DA3", "llm", "cluster.llm-genai", "ai"),
    ("paged-attention", "PagedAttention", "PagedAttention", "分页注意力", "vllm", "cluster.llm-genai", "ai"),
    ("speculative-decoding", "推测解码", "Speculative Decoding", "投机采样", "llm", "cluster.llm-genai", "ai"),
    ("structured-output", "结构化输出", "Structured Output", "JSON mode|constrained decoding", "llm", "cluster.llm-genai", "ai"),
    ("continued-pretrain", "继续预训练", "Continued Pretraining", "CPT|二次预训练", "llm", "cluster.llm-genai", "ai"),
    ("instruction-tuning", "指令微调", "Instruction Tuning", "指令跟随", "sft", "cluster.llm-genai", "ai"),
    ("rope", "RoPE", "RoPE", "旋转位置编码|Rotary Position Embedding", "llm", "cluster.llm-genai", "ai"),
    ("yarn", "YaRN", "YaRN", "Yet another RoPE extensioN", "rope", "cluster.llm-genai", "ai"),
    ("prefix-caching", "前缀缓存", "Prefix Caching", "automatic prefix caching", "vllm", "cluster.llm-genai", "ai"),
    ("continuous-batching", "连续批处理", "Continuous Batching", "iteration-level batching", "vllm", "cluster.llm-genai", "ai"),
    ("sglang", "SGLang", "SGLang", "sglang推理", "llm", "cluster.llm-genai", "ai"),
    ("lmdeploy", "LMDeploy", "LMDeploy", "InternLM LMDeploy", "llm", "cluster.llm-genai", "ai"),
    ("openllm", "OpenLLM", "OpenLLM", "BentoML OpenLLM", "llm", "cluster.llm-genai", "ai"),
    ("xinference", "Xinference", "Xinference", "Xorbits Inference", "llm", "cluster.llm-genai", "ai"),
    ("localai", "LocalAI", "LocalAI", "local ai", "llm", "cluster.llm-genai", "ai"),
    ("open-webui", "Open WebUI", "Open WebUI", "ollama webui", "ollama", "cluster.llm-genai", "ai"),
    ("sillytavern", "SillyTavern", "SillyTavern", "TavernAI", "llm", "cluster.llm-genai", "ai"),
    ("ragas", "RAGAS", "RAGAS", "RAG评估", "rag", "cluster.llm-genai", "ai"),
    ("llamaguard", "Llama Guard", "Llama Guard", "安全分类器", "llm", "cluster.llm-genai", "ai"),
    ("guardrails", "Guardrails", "Guardrails", "输出护栏|guardrails-ai", "llm", "cluster.llm-genai", "ai"),
    ("outlines", "Outlines", "Outlines", "结构化生成", "structured-output", "cluster.llm-genai", "ai"),
    ("instructor", "Instructor", "Instructor", "instructor库", "structured-output", "cluster.llm-genai", "ai"),
    ("dspy", "DSPy", "DSPy", "Stanford DSPy", "prompt-engineering", "cluster.llm-genai", "ai"),
    ("guidance", "Guidance", "Guidance", "Microsoft Guidance", "prompt-engineering", "cluster.llm-genai", "ai"),
    ("guidance-none", "", "", "", "", "cluster.llm-genai", "ai"),
]
AI = [r for r in AI if r[0] != "guidance-none"]
