"""人工智能方向其余技能簇：视觉、NLP、语音、强化学习、推荐、MLOps、基础、评测、智能体、加速、多模态。"""

AI_MORE = [
    # --- 计算机视觉 ---
    ("computer-vision", "计算机视觉", "Computer Vision", "CV|机器视觉", "", "cluster.cv", "ai"),
    ("opencv", "OpenCV", "OpenCV", "开源计算机视觉库", "computer-vision", "cluster.cv", "ai"),
    ("yolo", "YOLO", "YOLO", "YOLOv8|YOLOv11|Ultralytics", "computer-vision", "cluster.cv", "ai"),
    ("detectron2", "Detectron2", "Detectron2", "Facebook Detectron", "computer-vision", "cluster.cv", "ai"),
    ("mmdetection", "MMDetection", "MMDetection", "mmdet", "openmmlab", "cluster.cv", "ai"),
    ("mmsegmentation", "MMSegmentation", "MMSegmentation", "mmseg", "openmmlab", "cluster.cv", "ai"),
    ("mmpose", "MMPose", "MMPose", "姿态估计mmpose", "openmmlab", "cluster.cv", "ai"),
    ("sam", "Segment Anything", "Segment Anything", "SAM|SAM2|分割一切", "computer-vision", "cluster.cv", "ai"),
    # SD 走 BLOCKED_SURFACES（SD卡/标准差）；稳扩散是臆造译名，没人这么写。
    ("stable-diffusion", "Stable Diffusion", "Stable Diffusion", "SDXL", "computer-vision", "cluster.cv", "ai"),
    ("controlnet", "ControlNet", "ControlNet", "控制网络", "stable-diffusion", "cluster.cv", "ai"),
    ("gan", "生成对抗网络", "GAN", "Generative Adversarial Network", "computer-vision", "cluster.cv", "ai"),
    ("vit", "Vision Transformer", "Vision Transformer", "ViT|视觉Transformer", "computer-vision", "cluster.cv", "ai"),
    ("clip", "CLIP", "CLIP", "Contrastive Language-Image Pre-training", "computer-vision", "cluster.cv", "ai"),
    ("dinov2", "DINOv2", "DINOv2", "DINO", "computer-vision", "cluster.cv", "ai"),
    ("nerf", "NeRF", "NeRF", "神经辐射场|Neural Radiance Field", "computer-vision", "cluster.cv", "ai"),
    ("gaussian-splatting", "3D Gaussian Splatting", "3D Gaussian Splatting", "3DGS|高斯溅射", "computer-vision", "cluster.cv", "ai"),
    ("diffusion-model", "扩散模型", "Diffusion Model", "DDPM|去噪扩散", "computer-vision", "cluster.cv", "ai"),
    ("unet", "U-Net", "U-Net", "UNet", "computer-vision", "cluster.cv", "ai"),
    ("resnet", "ResNet", "ResNet", "残差网络", "computer-vision", "cluster.cv", "ai"),
    ("efficientnet", "EfficientNet", "EfficientNet", "EfficientNetV2", "computer-vision", "cluster.cv", "ai"),
    ("convnext", "ConvNeXt", "ConvNeXt", "ConvNext", "computer-vision", "cluster.cv", "ai"),
    ("detr", "DETR", "DETR", "Detection Transformer", "computer-vision", "cluster.cv", "ai"),
    ("mask-rcnn", "Mask R-CNN", "Mask R-CNN", "MaskRCNN", "computer-vision", "cluster.cv", "ai"),
    ("faster-rcnn", "Faster R-CNN", "Faster R-CNN", "FasterRCNN", "computer-vision", "cluster.cv", "ai"),
    ("object-detection", "目标检测", "Object Detection", "物体检测", "computer-vision", "cluster.cv", "ai"),
    ("image-segmentation", "图像分割", "Image Segmentation", "语义分割|实例分割", "computer-vision", "cluster.cv", "ai"),
    ("pose-estimation", "姿态估计", "Pose Estimation", "人体姿态|关键点检测", "computer-vision", "cluster.cv", "ai"),
    ("ocr", "光学字符识别", "OCR", "文字识别|光学识别", "computer-vision", "cluster.cv", "ai"),
    ("paddleocr", "PaddleOCR", "PaddleOCR", "飞桨OCR", "ocr", "cluster.cv", "ai"),
    ("easyocr", "EasyOCR", "EasyOCR", "easy ocr", "ocr", "cluster.cv", "ai"),
    ("tesseract", "Tesseract", "Tesseract", "Tesseract OCR", "ocr", "cluster.cv", "ai"),
    ("albumentations", "Albumentations", "Albumentations", "图像增强库", "computer-vision", "cluster.cv", "ai"),
    ("kornia", "Kornia", "Kornia", "kornia.geometry", "computer-vision", "cluster.cv", "ai"),
    ("mediapipe", "MediaPipe", "MediaPipe", "Google MediaPipe", "computer-vision", "cluster.cv", "ai"),
    ("insightface", "InsightFace", "InsightFace", "人脸识别InsightFace", "computer-vision", "cluster.cv", "ai"),
    ("facenet", "FaceNet", "FaceNet", "人脸嵌入", "computer-vision", "cluster.cv", "ai"),
    ("stylegan", "StyleGAN", "StyleGAN", "StyleGAN2|StyleGAN3", "gan", "cluster.cv", "ai"),
    ("vae", "变分自编码器", "VAE", "Variational Autoencoder", "computer-vision", "cluster.cv", "ai"),
    ("super-resolution", "超分辨率", "Super Resolution", "图像超分|SR", "computer-vision", "cluster.cv", "ai"),
    ("optical-flow", "光流", "Optical Flow", "光流估计", "computer-vision", "cluster.cv", "ai"),
    ("stereo-matching", "立体匹配", "Stereo Matching", "双目立体", "computer-vision", "cluster.cv", "ai"),
    ("slam-vision", "视觉SLAM", "Visual SLAM", "vSLAM", "computer-vision", "cluster.cv", "ai"),
    ("colmap", "COLMAP", "COLMAP", "运动恢复结构", "computer-vision", "cluster.cv", "ai"),
    ("open3d", "Open3D", "Open3D", "三维点云Open3D", "computer-vision", "cluster.cv", "ai"),
    ("pcl", "PCL", "Point Cloud Library", "点云库", "computer-vision", "cluster.cv", "ai"),
    ("mmdet3d", "MMDetection3D", "MMDetection3D", "三维检测", "openmmlab", "cluster.cv", "ai"),
    ("ultralytics", "Ultralytics", "Ultralytics", "ultralytics yolo", "yolo", "cluster.cv", "ai"),
    ("timm", "timm", "timm", "pytorch-image-models", "computer-vision", "cluster.cv", "ai"),
    ("torchvision", "torchvision", "torchvision", "PyTorch视觉", "pytorch", "cluster.cv", "ai"),
    ("labelme", "LabelMe", "LabelMe", "多边形标注", "computer-vision", "cluster.cv", "ai"),
    ("cvat", "CVAT", "CVAT", "Computer Vision Annotation Tool", "computer-vision", "cluster.cv", "ai"),
    # --- 多模态 ---
    ("multimodal", "多模态", "Multimodal", "多模态学习|跨模态", "", "cluster.multimodal", "ai"),
    ("llava", "LLaVA", "LLaVA", "Large Language and Vision Assistant", "multimodal", "cluster.multimodal", "ai"),
    ("blip", "BLIP", "BLIP", "BLIP-2", "multimodal", "cluster.multimodal", "ai"),
    ("qwen-vl", "Qwen-VL", "Qwen-VL", "千问视觉|Qwen2-VL", "qwen", "cluster.multimodal", "ai"),
    ("internvl", "InternVL", "InternVL", "书生多模态", "multimodal", "cluster.multimodal", "ai"),
    ("florence", "Florence", "Florence", "Florence-2", "multimodal", "cluster.multimodal", "ai"),
    ("grounding-dino", "Grounding DINO", "Grounding DINO", "开放词汇检测", "multimodal", "cluster.multimodal", "ai"),
    ("whisper-align", "视觉语言模型对齐", "Vision-Language Alignment", "图文对齐", "multimodal", "cluster.multimodal", "ai"),
    ("image-captioning", "图像描述", "Image Captioning", "看图说话", "multimodal", "cluster.multimodal", "ai"),
    ("vqa", "视觉问答", "Visual Question Answering", "VQA", "multimodal", "cluster.multimodal", "ai"),
    ("text-to-image", "文生图", "Text-to-Image", "文字生成图像|T2I", "multimodal", "cluster.multimodal", "ai"),
    ("text-to-video", "文生视频", "Text-to-Video", "T2V|Sora类", "multimodal", "cluster.multimodal", "ai"),
    ("text-to-3d", "文生三维", "Text-to-3D", "T2-3D", "multimodal", "cluster.multimodal", "ai"),
    ("comfyui", "ComfyUI", "ComfyUI", "Stable Diffusion节点", "stable-diffusion", "cluster.multimodal", "ai"),
    ("automatic1111", "AUTOMATIC1111", "AUTOMATIC1111", "A1111|SD WebUI", "stable-diffusion", "cluster.multimodal", "ai"),
    ("midjourney", "Midjourney", "Midjourney", "MJ绘图", "text-to-image", "cluster.multimodal", "ai"),
    ("dalle", "DALL·E", "DALL·E", "DALL-E|DALLE", "text-to-image", "cluster.multimodal", "ai"),
    ("sora", "Sora", "Sora", "OpenAI Sora", "text-to-video", "cluster.multimodal", "ai"),
    ("kling", "可灵", "Kling", "快手可灵", "text-to-video", "cluster.multimodal", "ai"),
    ("runway-ml", "Runway", "Runway", "RunwayML|Gen-3", "text-to-video", "cluster.multimodal", "ai"),
    # --- NLP ---
    ("nlp", "自然语言处理", "Natural Language Processing", "NLP|自然语言理解", "", "cluster.nlp", "ai"),
    ("spacy", "spaCy", "spaCy", "spacy", "nlp", "cluster.nlp", "ai"),
    ("nltk", "NLTK", "NLTK", "Natural Language Toolkit", "nlp", "cluster.nlp", "ai"),
    ("jieba", "jieba", "jieba", "结巴分词", "nlp", "cluster.nlp", "ai"),
    ("hanlp", "HanLP", "HanLP", "汉语NLP包", "nlp", "cluster.nlp", "ai"),
    ("ltp", "LTP", "LTP", "哈工大语言技术平台", "nlp", "cluster.nlp", "ai"),
    ("word2vec", "Word2Vec", "Word2Vec", "词向量Word2Vec", "nlp", "cluster.nlp", "ai"),
    ("glove", "GloVe", "GloVe", "Global Vectors", "nlp", "cluster.nlp", "ai"),
    ("fasttext", "FastText", "FastText", "fastText", "nlp", "cluster.nlp", "ai"),
    ("crf", "条件随机场", "CRF", "Conditional Random Field", "nlp", "cluster.nlp", "ai"),
    ("ner", "命名实体识别", "Named Entity Recognition", "NER|实体识别", "nlp", "cluster.nlp", "ai"),
    ("pos-tagging", "词性标注", "POS Tagging", "词性识别", "nlp", "cluster.nlp", "ai"),
    ("sentiment-analysis", "情感分析", "Sentiment Analysis", "舆情分析", "nlp", "cluster.nlp", "ai"),
    ("text-classification", "文本分类", "Text Classification", "文档分类", "nlp", "cluster.nlp", "ai"),
    ("machine-translation", "机器翻译", "Machine Translation", "NMT|神经机器翻译", "nlp", "cluster.nlp", "ai"),
    ("summarization", "文本摘要", "Summarization", "自动摘要", "nlp", "cluster.nlp", "ai"),
    ("question-answering", "问答", "Question Answering", "QA|阅读理解", "nlp", "cluster.nlp", "ai"),
    ("coreference", "指代消解", "Coreference Resolution", "共指消解", "nlp", "cluster.nlp", "ai"),
    ("dependency-parsing", "依存句法分析", "Dependency Parsing", "句法分析", "nlp", "cluster.nlp", "ai"),
    ("topic-model", "主题模型", "Topic Model", "LDA主题", "nlp", "cluster.nlp", "ai"),
    ("bm25", "BM25", "BM25", "Okapi BM25", "nlp", "cluster.nlp", "ai"),
    ("tfidf", "TF-IDF", "TF-IDF", "词频-逆文档频率", "nlp", "cluster.nlp", "ai"),
    ("sentence-transformers", "Sentence Transformers", "Sentence Transformers", "sbert|sentence-transformers", "embedding-model", "cluster.nlp", "ai"),
    ("bge", "BGE", "BGE", "BAAI General Embedding|智源BGE", "embedding-model", "cluster.nlp", "ai"),
    ("gte", "GTE", "GTE", "Alibaba GTE", "embedding-model", "cluster.nlp", "ai"),
    ("m3e", "M3E", "M3E", "Moka Massive Mixed Embedding", "embedding-model", "cluster.nlp", "ai"),
    ("text2vec", "text2vec", "text2vec", "shibing624", "embedding-model", "cluster.nlp", "ai"),
    ("sentencepiece", "SentencePiece", "SentencePiece", "unigram分词", "tokenizer", "cluster.nlp", "ai"),
    ("bpe", "BPE", "Byte Pair Encoding", "字节对编码", "tokenizer", "cluster.nlp", "ai"),
    ("kenlm", "KenLM", "KenLM", "n-gram语言模型", "nlp", "cluster.nlp", "ai"),
    ("opennmt", "OpenNMT", "OpenNMT", "OpenNMT-py", "machine-translation", "cluster.nlp", "ai"),
    ("fairseq", "fairseq", "fairseq", "Facebook fairseq", "nlp", "cluster.nlp", "ai"),
    ("stanza", "Stanza", "Stanza", "Stanford Stanza", "nlp", "cluster.nlp", "ai"),
    ("pkuseg", "pkuseg", "pkuseg", "北大分词", "nlp", "cluster.nlp", "ai"),
    ("thulac", "THULAC", "THULAC", "清华分词", "nlp", "cluster.nlp", "ai"),
    # --- 语音 ---
    ("speech", "语音处理", "Speech Processing", "语音技术", "", "cluster.speech", "ai"),
    ("asr", "语音识别", "Automatic Speech Recognition", "ASR|语音转写", "speech", "cluster.speech", "ai"),
    ("tts", "语音合成", "Text-to-Speech", "TTS|语音生成", "speech", "cluster.speech", "ai"),
    ("whisper", "Whisper", "Whisper", "OpenAI Whisper", "asr", "cluster.speech", "ai"),
    ("kaldi", "Kaldi", "Kaldi", "Kaldi ASR", "asr", "cluster.speech", "ai"),
    ("wenet", "WeNet", "WeNet", "微信WeNet", "asr", "cluster.speech", "ai"),
    ("funasr", "FunASR", "FunASR", "达摩院FunASR", "asr", "cluster.speech", "ai"),
    ("paraformer", "Paraformer", "Paraformer", "非自回归ASR", "funasr", "cluster.speech", "ai"),
    ("conformer", "Conformer", "Conformer", "Convolution-augmented Transformer", "asr", "cluster.speech", "ai"),
    ("wav2vec", "wav2vec", "wav2vec", "wav2vec 2.0", "asr", "cluster.speech", "ai"),
    ("hubert", "HuBERT", "HuBERT", "Hidden-Unit BERT", "asr", "cluster.speech", "ai"),
    ("speaker-verification", "说话人确认", "Speaker Verification", "声纹识别|说话人识别", "speech", "cluster.speech", "ai"),
    ("diarization", "说话人分离", "Speaker Diarization", "谁在何时说话", "speech", "cluster.speech", "ai"),
    ("kws", "关键词检出", "Keyword Spotting", "KWS|唤醒词", "speech", "cluster.speech", "ai"),
    ("speech-enhancement", "语音增强", "Speech Enhancement", "降噪|去混响", "speech", "cluster.speech", "ai"),
    ("vocoder", "声码器", "Vocoder", "HiFi-GAN|WaveNet声码器", "tts", "cluster.speech", "ai"),
    ("tacotron", "Tacotron", "Tacotron", "Tacotron2", "tts", "cluster.speech", "ai"),
    ("fastspeech", "FastSpeech", "FastSpeech", "FastSpeech2", "tts", "cluster.speech", "ai"),
    ("vits", "VITS", "VITS", "条件变分TTS", "tts", "cluster.speech", "ai"),
    ("chattts", "ChatTTS", "ChatTTS", "对话语音合成", "tts", "cluster.speech", "ai"),
    ("fish-speech", "Fish Speech", "Fish Speech", "开源TTS", "tts", "cluster.speech", "ai"),
    ("espnet", "ESPnet", "ESPnet", "End-to-End Speech", "speech", "cluster.speech", "ai"),
    ("torchaudio", "torchaudio", "torchaudio", "PyTorch音频", "speech", "cluster.speech", "ai"),
    # --- 强化学习 ---
    ("reinforcement-learning", "强化学习", "Reinforcement Learning", "RL|增强学习", "", "cluster.rl", "ai"),
    ("gymnasium", "Gymnasium", "Gymnasium", "OpenAI Gym|gym", "reinforcement-learning", "cluster.rl", "ai"),
    ("stable-baselines3", "Stable-Baselines3", "Stable-Baselines3", "SB3", "reinforcement-learning", "cluster.rl", "ai"),
    ("mujoco", "MuJoCo", "MuJoCo", "Multi-Joint dynamics with Contact", "reinforcement-learning", "cluster.rl", "ai"),
    ("isaac-gym", "Isaac Gym", "Isaac Gym", "NVIDIA Isaac Gym", "reinforcement-learning", "cluster.rl", "ai"),
    ("isaac-sim", "Isaac Sim", "Isaac Sim", "NVIDIA Isaac Sim", "reinforcement-learning", "cluster.rl", "ai"),
    ("ppo", "近端策略优化", "PPO", "Proximal Policy Optimization", "reinforcement-learning", "cluster.rl", "ai"),
    ("dqn", "深度Q网络", "DQN", "Deep Q-Network", "reinforcement-learning", "cluster.rl", "ai"),
    ("sac", "软演员评论家", "SAC", "Soft Actor-Critic", "reinforcement-learning", "cluster.rl", "ai"),
    ("td3", "TD3", "TD3", "Twin Delayed DDPG", "reinforcement-learning", "cluster.rl", "ai"),
    ("ddpg", "DDPG", "DDPG", "Deep Deterministic Policy Gradient", "reinforcement-learning", "cluster.rl", "ai"),
    ("a3c", "A3C", "A3C", "Asynchronous Advantage Actor-Critic", "reinforcement-learning", "cluster.rl", "ai"),
    ("mcts", "蒙特卡洛树搜索", "MCTS", "Monte Carlo Tree Search", "reinforcement-learning", "cluster.rl", "ai"),
    ("imitation-learning", "模仿学习", "Imitation Learning", "行为克隆|IL", "reinforcement-learning", "cluster.rl", "ai"),
    ("offline-rl", "离线强化学习", "Offline RL", "batch RL", "reinforcement-learning", "cluster.rl", "ai"),
    ("multi-agent-rl", "多智能体强化学习", "Multi-Agent RL", "MARL", "reinforcement-learning", "cluster.rl", "ai"),
    ("rllib", "RLlib", "RLlib", "Ray RLlib", "reinforcement-learning", "cluster.rl", "ai"),
    ("pettingzoo", "PettingZoo", "PettingZoo", "多智能体环境", "multi-agent-rl", "cluster.rl", "ai"),
    ("dm-control", "dm_control", "dm_control", "DeepMind Control Suite", "reinforcement-learning", "cluster.rl", "ai"),
    ("envpool", "EnvPool", "EnvPool", "并行环境", "reinforcement-learning", "cluster.rl", "ai"),
    # --- 推荐系统 ---
    ("recsys", "推荐系统", "Recommender System", "个性化推荐", "", "cluster.recsys", "ai"),
    ("deepfm", "DeepFM", "DeepFM", "深度因子分解机", "recsys", "cluster.recsys", "ai"),
    ("din", "DIN", "DIN", "Deep Interest Network", "recsys", "cluster.recsys", "ai"),
    ("wide-deep", "Wide & Deep", "Wide & Deep", "Wide and Deep", "recsys", "cluster.recsys", "ai"),
    ("two-tower", "双塔模型", "Two-Tower", "双塔召回", "recsys", "cluster.recsys", "ai"),
    ("dcn", "DCN", "Deep & Cross Network", "Deep Cross Network", "recsys", "cluster.recsys", "ai"),
    ("mmoe", "MMoE", "MMoE", "Multi-gate Mixture-of-Experts", "recsys", "cluster.recsys", "ai"),
    ("ctr-prediction", "点击率预估", "CTR Prediction", "CTR|CVR", "recsys", "cluster.recsys", "ai"),
    ("itemcf", "物品协同过滤", "ItemCF", "Item-based CF", "recsys", "cluster.recsys", "ai"),
    ("usercf", "用户协同过滤", "UserCF", "User-based CF", "recsys", "cluster.recsys", "ai"),
    ("als", "ALS", "ALS", "交替最小二乘", "recsys", "cluster.recsys", "ai"),
    ("bandit", "多臂老虎机", "Multi-Armed Bandit", "Bandit|上下文老虎机", "recsys", "cluster.recsys", "ai"),
    ("ann-search", "近似最近邻检索", "ANN Search", "向量召回|HNSW", "recsys", "cluster.recsys", "ai"),
    ("deepctr", "DeepCTR", "DeepCTR", "deepctr-torch", "recsys", "cluster.recsys", "ai"),
    ("easyrec", "EasyRec", "EasyRec", "阿里EasyRec", "recsys", "cluster.recsys", "ai"),
    # --- 评测与对齐 ---
    ("model-eval", "模型评测", "Model Evaluation", "评测集|benchmark", "", "cluster.eval", "ai"),
    ("bleu", "BLEU", "BLEU", "Bilingual Evaluation Understudy", "model-eval", "cluster.eval", "ai"),
    ("rouge", "ROUGE", "ROUGE", "Recall-Oriented Understudy", "model-eval", "cluster.eval", "ai"),
    ("bertscore", "BERTScore", "BERTScore", "BERT分数", "model-eval", "cluster.eval", "ai"),
    ("perplexity", "困惑度", "Perplexity", "PPL", "model-eval", "cluster.eval", "ai"),
    ("llm-as-judge", "大模型评委", "LLM-as-Judge", "LLM评判", "model-eval", "cluster.eval", "ai"),
    ("mt-bench", "MT-Bench", "MT-Bench", "多轮对话评测", "model-eval", "cluster.eval", "ai"),
    ("opencompass", "OpenCompass", "OpenCompass", "司南评测", "model-eval", "cluster.eval", "ai"),
    ("lm-eval-harness", "lm-evaluation-harness", "lm-evaluation-harness", "EleutherAI eval", "model-eval", "cluster.eval", "ai"),
    ("hallucination-detect", "幻觉检测", "Hallucination Detection", "事实性|幻觉", "model-eval", "cluster.eval", "ai"),
    ("red-teaming", "红队测试", "Red Teaming", "对抗测试|越狱评测", "model-eval", "cluster.eval", "ai"),
    ("alignment", "对齐", "Alignment", "AI对齐|价值对齐", "llm", "cluster.eval", "ai"),
    ("constitutional-ai", "宪法AI", "Constitutional AI", "CAI", "alignment", "cluster.eval", "ai"),
    ("human-eval-coding", "HumanEval", "HumanEval", "代码生成评测", "model-eval", "cluster.eval", "ai"),
    ("mmlu", "MMLU", "MMLU", "Massive Multitask Language Understanding", "model-eval", "cluster.eval", "ai"),
    ("cmmlu", "CMMLU", "CMMLU", "中文MMLU", "model-eval", "cluster.eval", "ai"),
    ("ceval", "C-Eval", "C-Eval", "CEval", "model-eval", "cluster.eval", "ai"),
    ("truthfulqa", "TruthfulQA", "TruthfulQA", "真实性问答", "model-eval", "cluster.eval", "ai"),
    ("safety-eval", "安全评测", "Safety Evaluation", "内容安全评测", "model-eval", "cluster.eval", "ai"),
    # --- 智能体 ---
    ("ai-agent", "智能体", "AI Agent", "AI智能体|AI代理", "", "cluster.agent", "ai"),
    ("multi-agent", "多智能体", "Multi-Agent System", "多智能体系统|MAS", "ai-agent", "cluster.agent", "ai"),
    ("autogen", "AutoGen", "AutoGen", "Microsoft AutoGen", "ai-agent", "cluster.agent", "ai"),
    ("crewai", "CrewAI", "CrewAI", "crew ai", "ai-agent", "cluster.agent", "ai"),
    ("langgraph", "LangGraph", "LangGraph", "LangChain Graph", "langchain", "cluster.agent", "ai"),
    ("metagpt", "MetaGPT", "MetaGPT", "深度多智能体", "ai-agent", "cluster.agent", "ai"),
    ("open-interpreter", "Open Interpreter", "Open Interpreter", "openinterpreter", "ai-agent", "cluster.agent", "ai"),
    ("computer-use", "计算机使用", "Computer Use", "GUI Agent|电脑操作智能体", "ai-agent", "cluster.agent", "ai"),
    ("browser-use", "浏览器使用", "Browser Use", "网页智能体", "ai-agent", "cluster.agent", "ai"),
    ("agent-memory", "智能体记忆", "Agent Memory", "长期记忆|记忆模块", "ai-agent", "cluster.agent", "ai"),
    ("agent-planning", "智能体规划", "Agent Planning", "任务规划|分解", "ai-agent", "cluster.agent", "ai"),
    ("a2a-protocol", "A2A协议", "Agent-to-Agent Protocol", "A2A", "multi-agent", "cluster.agent", "ai"),
    ("swarm", "Swarm", "Swarm", "OpenAI Swarm", "multi-agent", "cluster.agent", "ai"),
    ("camel-agent", "CAMEL", "CAMEL", "Communicative Agents", "multi-agent", "cluster.agent", "ai"),
    ("autogpt", "AutoGPT", "AutoGPT", "Significant Gravitas", "ai-agent", "cluster.agent", "ai"),
    ("babyagi", "BabyAGI", "BabyAGI", "任务驱动智能体", "ai-agent", "cluster.agent", "ai"),
    ("code-act", "CodeAct", "CodeAct", "代码行动智能体", "ai-agent", "cluster.agent", "ai"),
    # --- MLOps ---
    ("mlops", "MLOps", "MLOps", "机器学习运维|ML工程", "", "cluster.mlops", "ai"),
    ("mlflow", "MLflow", "MLflow", "Databricks MLflow", "mlops", "cluster.mlops", "ai"),
    ("wandb", "Weights & Biases", "Weights & Biases", "W&B|wandb", "mlops", "cluster.mlops", "ai"),
    ("dvc", "DVC", "DVC", "Data Version Control", "mlops", "cluster.mlops", "ai"),
    ("kubeflow", "Kubeflow", "Kubeflow", "KFP|Kubeflow Pipelines", "mlops", "cluster.mlops", "ai"),
    ("tfx", "TFX", "TFX", "TensorFlow Extended", "mlops", "cluster.mlops", "ai"),
    ("feast", "Feast", "Feast", "特征存储Feast", "mlops", "cluster.mlops", "ai"),
    ("bentoml", "BentoML", "BentoML", "bento ml", "mlops", "cluster.mlops", "ai"),
    ("seldon", "Seldon", "Seldon Core", "Seldon部署", "mlops", "cluster.mlops", "ai"),
    ("kserve", "KServe", "KServe", "KFServing", "mlops", "cluster.mlops", "ai"),
    ("triton", "Triton Inference Server", "Triton Inference Server", "NVIDIA Triton", "mlops", "cluster.mlops", "ai"),
    ("torchserve", "TorchServe", "TorchServe", "PyTorch Serve", "mlops", "cluster.mlops", "ai"),
    ("tf-serving", "TensorFlow Serving", "TensorFlow Serving", "TF Serving", "mlops", "cluster.mlops", "ai"),
    ("sagemaker", "Amazon SageMaker", "Amazon SageMaker", "SageMaker", "mlops", "cluster.mlops", "ai"),
    ("vertex-ai", "Vertex AI", "Vertex AI", "Google Vertex", "mlops", "cluster.mlops", "ai"),
    ("azure-ml", "Azure Machine Learning", "Azure Machine Learning", "Azure ML", "mlops", "cluster.mlops", "ai"),
    ("label-studio", "Label Studio", "Label Studio", "Heartex Label Studio", "mlops", "cluster.mlops", "ai"),
    ("model-registry", "模型注册表", "Model Registry", "模型仓库", "mlops", "cluster.mlops", "ai"),
    ("feature-store", "特征存储", "Feature Store", "特征平台", "mlops", "cluster.mlops", "ai"),
    ("data-drift", "数据漂移", "Data Drift", "分布漂移|concept drift", "mlops", "cluster.mlops", "ai"),
    ("model-monitor", "模型监控", "Model Monitoring", "在线监控", "mlops", "cluster.mlops", "ai"),
    ("ab-testing", "A/B测试", "A/B Testing", "分流实验", "mlops", "cluster.mlops", "ai"),
    ("ray", "Ray", "Ray", "Anyscale Ray|Ray Core", "mlops", "cluster.mlops", "ai"),
    ("ray-serve", "Ray Serve", "Ray Serve", "rayserve", "ray", "cluster.mlops", "ai"),
    ("optuna", "Optuna", "Optuna", "超参搜索Optuna", "mlops", "cluster.mlops", "ai"),
    ("hyperopt", "Hyperopt", "Hyperopt", "贝叶斯超参", "mlops", "cluster.mlops", "ai"),
    ("nni", "NNI", "NNI", "Neural Network Intelligence|微软NNI", "mlops", "cluster.mlops", "ai"),
    ("clearml", "ClearML", "ClearML", "allegro ClearML", "mlops", "cluster.mlops", "ai"),
    ("neptune", "Neptune", "Neptune.ai", "实验跟踪Neptune", "mlops", "cluster.mlops", "ai"),
    ("comet-ml", "Comet", "Comet ML", "comet.ml", "mlops", "cluster.mlops", "ai"),
    ("dvc-studio", "DVC Studio", "DVC Studio", "iterative studio", "dvc", "cluster.mlops", "ai"),
    ("prefect", "Prefect", "Prefect", "工作流Prefect", "mlops", "cluster.mlops", "ai"),
    ("dagster", "Dagster", "Dagster", "数据编排Dagster", "mlops", "cluster.mlops", "ai"),
    ("metaflow", "Metaflow", "Metaflow", "Netflix Metaflow", "mlops", "cluster.mlops", "ai"),
    ("kedro", "Kedro", "Kedro", "QuantumBlack Kedro", "mlops", "cluster.mlops", "ai"),
    ("pycaret", "PyCaret", "PyCaret", "低代码ML", "mlops", "cluster.mlops", "ai"),
    ("h2o", "H2O", "H2O.ai", "H2O AutoML", "mlops", "cluster.mlops", "ai"),
    ("automl", "自动机器学习", "AutoML", "自动建模", "mlops", "cluster.mlops", "ai"),
    ("onnx-runtime", "ONNX Runtime", "ONNX Runtime", "ORT", "onnx", "cluster.mlops", "ai"),
    # --- 加速 ---
    ("cuda", "CUDA", "CUDA", "NVIDIA CUDA", "", "cluster.accel", "ai"),
    ("cudnn", "cuDNN", "cuDNN", "CUDA Deep Neural Network", "cuda", "cluster.accel", "ai"),
    ("nccl", "NCCL", "NCCL", "NVIDIA Collective Communications", "cuda", "cluster.accel", "ai"),
    ("tensorrt", "TensorRT", "TensorRT", "NVIDIA TensorRT", "cuda", "cluster.accel", "ai"),
    ("openvino", "OpenVINO", "OpenVINO", "Intel OpenVINO", "", "cluster.accel", "ai"),
    ("coreml", "Core ML", "Core ML", "Apple Core ML", "", "cluster.accel", "ai"),
    ("tpu", "TPU", "TPU", "Tensor Processing Unit", "", "cluster.accel", "ai"),
    ("npu", "NPU", "NPU", "神经网络处理器|AI加速器", "", "cluster.accel", "ai"),
    ("ascend", "昇腾", "Ascend", "华为昇腾|Ascend NPU", "npu", "cluster.accel", "ai"),
    ("cann", "CANN", "CANN", "Compute Architecture for Neural Networks", "ascend", "cluster.accel", "ai"),
    ("rocm", "ROCm", "ROCm", "AMD ROCm", "", "cluster.accel", "ai"),
    ("oneapi", "oneAPI", "oneAPI", "Intel oneAPI", "", "cluster.accel", "ai"),
    ("cutlass", "CUTLASS", "CUTLASS", "CUDA Templates for Linear Algebra", "cuda", "cluster.accel", "ai"),
    ("triton-lang", "Triton语言", "Triton Language", "OpenAI Triton|triton kernel", "cuda", "cluster.accel", "ai"),
    ("torch-compile", "torch.compile", "torch.compile", "PyTorch 2编译", "pytorch", "cluster.accel", "ai"),
    ("xla", "XLA", "XLA", "Accelerated Linear Algebra", "tensorflow", "cluster.accel", "ai"),
    ("mixed-precision", "混合精度", "Mixed Precision", "AMP|FP16训练", "deep-learning", "cluster.accel", "ai"),
    ("tensor-parallel", "张量并行", "Tensor Parallelism", "TP", "llm", "cluster.accel", "ai"),
    ("pipeline-parallel", "流水线并行", "Pipeline Parallelism", "PP", "llm", "cluster.accel", "ai"),
    ("data-parallel", "数据并行", "Data Parallelism", "DDP|DP", "deep-learning", "cluster.accel", "ai"),
    ("gradient-checkpointing", "梯度检查点", "Gradient Checkpointing", "activation checkpointing", "deep-learning", "cluster.accel", "ai"),
    ("nvlink", "NVLink", "NVLink", "NVIDIA NVLink", "cuda", "cluster.accel", "ai"),
    ("infiniband", "InfiniBand", "InfiniBand", "IB网络", "", "cluster.accel", "ai"),
    ("rdma", "RDMA", "RDMA", "Remote Direct Memory Access", "infiniband", "cluster.accel", "ai"),
    ("horovod", "Horovod", "Horovod", "分布式Horovod", "deep-learning", "cluster.accel", "ai"),
    ("nccl-tests", "集合通信", "Collective Communication", "allreduce|allgather", "nccl", "cluster.accel", "ai"),
    # --- 机器学习基础 ---
    ("linear-algebra", "线性代数", "Linear Algebra", "矩阵运算", "", "cluster.ml-theory", "ai"),
    ("probability", "概率统计", "Probability and Statistics", "数理统计", "", "cluster.ml-theory", "ai"),
    ("optimization", "最优化", "Optimization", "凸优化|数值优化", "", "cluster.ml-theory", "ai"),
    ("information-theory", "信息论", "Information Theory", "熵|互信息", "", "cluster.ml-theory", "ai"),
    ("bayesian", "贝叶斯方法", "Bayesian Methods", "贝叶斯推断", "probability", "cluster.ml-theory", "ai"),
    ("svm", "支持向量机", "SVM", "Support Vector Machine", "machine-learning", "cluster.ml-theory", "ai"),
    ("decision-tree", "决策树", "Decision Tree", "CART", "machine-learning", "cluster.ml-theory", "ai"),
    ("random-forest", "随机森林", "Random Forest", "RF", "machine-learning", "cluster.ml-theory", "ai"),
    ("gbdt", "梯度提升树", "GBDT", "Gradient Boosting Decision Tree", "machine-learning", "cluster.ml-theory", "ai"),
    ("clustering", "聚类", "Clustering", "K-Means|层次聚类", "machine-learning", "cluster.ml-theory", "ai"),
    ("pca", "主成分分析", "PCA", "Principal Component Analysis", "machine-learning", "cluster.ml-theory", "ai"),
    ("gradient-descent", "梯度下降", "Gradient Descent", "SGD|Adam", "optimization", "cluster.ml-theory", "ai"),
    ("backprop", "反向传播", "Backpropagation", "BP算法", "deep-learning", "cluster.ml-theory", "ai"),
    ("regularization", "正则化", "Regularization", "L1|L2|权重衰减", "machine-learning", "cluster.ml-theory", "ai"),
    ("dropout", "Dropout", "Dropout", "随机失活", "deep-learning", "cluster.ml-theory", "ai"),
    ("batch-norm", "批归一化", "Batch Normalization", "BN", "deep-learning", "cluster.ml-theory", "ai"),
    ("layer-norm", "层归一化", "Layer Normalization", "LN", "deep-learning", "cluster.ml-theory", "ai"),
    ("attention", "注意力机制", "Attention", "Self-Attention|自注意力", "deep-learning", "cluster.ml-theory", "ai"),
    ("transformer", "Transformer", "Transformer", "变压器模型", "attention", "cluster.ml-theory", "ai"),
    ("cnn", "卷积神经网络", "CNN", "Convolutional Neural Network", "deep-learning", "cluster.ml-theory", "ai"),
    ("rnn", "循环神经网络", "RNN", "Recurrent Neural Network", "deep-learning", "cluster.ml-theory", "ai"),
    ("lstm", "LSTM", "LSTM", "长短期记忆", "rnn", "cluster.ml-theory", "ai"),
    ("gru", "GRU", "GRU", "Gated Recurrent Unit", "rnn", "cluster.ml-theory", "ai"),
    ("loss-function", "损失函数", "Loss Function", "交叉熵|MSE", "machine-learning", "cluster.ml-theory", "ai"),
    ("contrastive-learning", "对比学习", "Contrastive Learning", "InfoNCE", "deep-learning", "cluster.ml-theory", "ai"),
    ("self-supervised", "自监督学习", "Self-Supervised Learning", "SSL", "deep-learning", "cluster.ml-theory", "ai"),
    ("transfer-learning", "迁移学习", "Transfer Learning", "微调迁移", "machine-learning", "cluster.ml-theory", "ai"),
    ("meta-learning", "元学习", "Meta-Learning", "学会学习", "machine-learning", "cluster.ml-theory", "ai"),
    ("continual-learning", "持续学习", "Continual Learning", "灾难性遗忘", "machine-learning", "cluster.ml-theory", "ai"),
    ("causal-inference", "因果推断", "Causal Inference", "因果效应", "machine-learning", "cluster.ml-theory", "ai"),
    ("time-series", "时间序列", "Time Series", "时序预测", "machine-learning", "cluster.ml-theory", "ai"),
    ("anomaly-detection", "异常检测", "Anomaly Detection", "离群点", "machine-learning", "cluster.ml-theory", "ai"),
    ("gaussian-process", "高斯过程", "Gaussian Process", "GP回归", "machine-learning", "cluster.ml-theory", "ai"),
    ("ensemble-learning", "集成学习", "Ensemble Learning", "bagging|boosting|stacking", "machine-learning", "cluster.ml-theory", "ai"),
    ("graph-neural-net", "图神经网络", "Graph Neural Network", "GNN|GCN|GAT", "deep-learning", "cluster.ml-theory", "ai"),
    ("knowledge-distill", "知识蒸馏", "Knowledge Distillation", "KD|教师学生网络", "deep-learning", "cluster.ml-theory", "ai"),
    ("neural-architecture-search", "神经架构搜索", "Neural Architecture Search", "NAS", "deep-learning", "cluster.ml-theory", "ai"),
    ("federated-learning", "联邦学习", "Federated Learning", "联邦训练", "machine-learning", "cluster.ml-theory", "ai"),
    ("differential-privacy", "差分隐私", "Differential Privacy", "DP-SGD", "machine-learning", "cluster.ml-theory", "ai"),
    ("explainable-ai", "可解释人工智能", "Explainable AI", "XAI|SHAP|LIME", "machine-learning", "cluster.ml-theory", "ai"),
    ("imbalanced-learning", "不平衡学习", "Imbalanced Learning", "SMOTE|类别不平衡", "machine-learning", "cluster.ml-theory", "ai"),
    ("semi-supervised", "半监督学习", "Semi-Supervised Learning", "伪标签", "machine-learning", "cluster.ml-theory", "ai"),
    ("active-learning", "主动学习", "Active Learning", "查询策略", "machine-learning", "cluster.ml-theory", "ai"),
    ("metric-learning", "度量学习", "Metric Learning", "三元组损失", "deep-learning", "cluster.ml-theory", "ai"),
    ("numpy", "NumPy", "NumPy", "numpy数组", "", "cluster.ml-theory", "ai"),
    ("pandas", "pandas", "pandas", "Python数据分析", "", "cluster.ml-theory", "ai"),
    ("scipy", "SciPy", "SciPy", "科学计算SciPy", "", "cluster.ml-theory", "ai"),
    ("matplotlib", "Matplotlib", "Matplotlib", "pyplot", "", "cluster.ml-theory", "ai"),
    ("seaborn", "seaborn", "seaborn", "统计可视化", "matplotlib", "cluster.ml-theory", "ai"),
    ("plotly", "Plotly", "Plotly", "交互可视化", "", "cluster.ml-theory", "ai"),
]
